"""The nine required documents, as pure functions over the survey dict.

Every generator here takes `SurveyResult.to_dict()` and returns a string. None
of them touches the filesystem, re-reads a Sandbox file, or consults anything
the JSON does not already contain. That is what makes the JSON and the prose
incapable of disagreeing, and it is what lets the whole reporting surface be
tested against hand-written dictionaries with no Sandbox anywhere in sight.

ONE RULE GOVERNS ALL NINE DOCUMENTS: **no report ever quotes file content.**

Not an excerpt, not a matched substring, not "the line that triggered the
detector", not a first paragraph, not a title read from inside a document. The
reports are built from paths, sizes, timestamps, hashes, class names, rule ids,
detector ids and counts -- metadata about content, never content. Adopting that
as an absolute rather than as a special case for the sensitive-material report
buys three things at once:

  * the sensitive report cannot leak a credential, because there is no
    machinery anywhere that could carry one into a document;
  * no report can accidentally reproduce an attestation of approval by the
    programme's principal, which this mission is forbidden to manufacture or
    to circulate as though it were authority;
  * the outputs are safe to email, paste and archive without anyone having to
    first check whether this particular Sandbox contained something private.

Every document carries the same header block: who generated it, when, which
Sandbox path was read, where the outputs went, the read-only declaration, and
the statement that nothing in it is accepted doctrine or a Mike decision. The
header is generated from one function, so no document can be shipped without it.
"""

from __future__ import annotations

import csv
import io
import json
from typing import Any, Callable, Iterable

_ABSENT = "ABSENT"


# --------------------------------------------------------------------------- header

def _rule_line() -> str:
    return "---"


def header_lines(data: dict[str, Any], title: str) -> list[str]:
    """The mandatory header, identical in shape across all nine documents."""
    performed = bool(data["survey_performed"])
    lines = [
        f"# {title}",
        "",
        f"- **Generated by:** {data['generated_by']}",
        f"- **Generated (UTC):** {data['generated_at']}",
        f"- **Tool:** `{data['tool']}` {data['tool_version']} — run `{data['run_id']}`",
        f"- **Sandbox path read:** `{data['sandbox_root']}`",
        f"- **Output path:** `{data['output_root']}`",
        f"- **Survey status:** `{data['status']}`",
        "",
        f"> **{data['read_only_declaration']}**",
        ">",
        f"> **{data['authority_declaration']}**",
        "",
    ]
    if not performed:
        lines += [
            "> **THIS SURVEY HAS NOT BEEN RUN.** This document is a template showing the "
            "shape of the output. No file under the Sandbox path above has been read, "
            "listed, hashed or classified.",
            ">",
            f"> Reason: {data['absent_reason']}",
            ">",
            f"> Every content claim in this document is `{_ABSENT}` — meaning the step was "
            "not performed, not that the material does not exist.",
            "",
        ]
    lines.append(_rule_line())
    lines.append("")
    return lines


def _absent_section(what: str) -> list[str]:
    return [
        f"## {what}",
        "",
        f"`{_ABSENT}` — the survey was not performed, so nothing is claimed here. "
        "Run the tool on the machine that holds the Sandbox (see "
        "`docs/readiness/SANDBOX_SURVEY_PROCEDURE.md`) and this section will be "
        "populated from what is actually on disk.",
        "",
    ]


def _cell(text: Any) -> str:
    """Markdown table cell. Pipes escaped; nothing else altered."""
    return str(text).replace("|", "\\|").replace("\n", " ")


def _table(headings: Iterable[str], rows: Iterable[Iterable[Any]]) -> list[str]:
    headings = list(headings)
    lines = [
        "| " + " | ".join(headings) + " |",
        "| " + " | ".join("---" for _ in headings) + " |",
    ]
    body = [
        "| " + " | ".join(_cell(value) for value in row) + " |"
        for row in rows
    ]
    if not body:
        return lines + ["| " + " | ".join("_none_" if index == 0 else "" for index in range(len(headings))) + " |"]
    return lines + body


def _yes_no(value: Any) -> str:
    return "Y" if value else "N"


def _classes(record: dict[str, Any]) -> str:
    return ", ".join(record["secondary_classes"]) or "-"


def _footer(data: dict[str, Any]) -> list[str]:
    return [
        "",
        _rule_line(),
        "",
        f"_{data['read_only_declaration']}_  ",
        f"_{data['authority_declaration']}_  ",
        "_No file content is quoted anywhere in this document — only paths, sizes, "
        "timestamps, hashes, class names, rule identifiers and counts._",
        "",
    ]


def _render(lines: list[str]) -> str:
    return "\n".join(lines).rstrip() + "\n"


# --------------------------------------------------------------------------- 1. inventory

INVENTORY_COLUMNS = (
    "path", "size_bytes", "modified_utc", "sha256", "primary_class",
    "secondary_classes", "dispatch_related", "text_confidence", "read_error",
    "duplicate_of", "classification_reasons",
)


def inventory_csv(data: dict[str, Any]) -> str:
    """Machine-readable inventory.

    The mandatory header is emitted as ``#``-prefixed comment lines above the
    column row. Readers must skip lines beginning with ``#`` -- which pandas,
    R and `csv` all do with one argument -- and in exchange the file carries its
    provenance and its read-only declaration with it, so a CSV that has been
    copied out of the output folder still says where it came from and what it
    is not.
    """
    buffer = io.StringIO()
    comments = [
        f"Generated by: {data['generated_by']}",
        f"Generated (UTC): {data['generated_at']}",
        f"Tool: {data['tool']} {data['tool_version']} run {data['run_id']}",
        f"Sandbox path read: {data['sandbox_root']}",
        f"Output path: {data['output_root']}",
        f"Survey status: {data['status']}",
        data["read_only_declaration"],
        data["authority_declaration"],
    ]
    if not data["survey_performed"]:
        comments.append(
            f"THIS SURVEY HAS NOT BEEN RUN — every content claim is {_ABSENT}. "
            f"Reason: {data['absent_reason']}"
        )
    for comment in comments:
        buffer.write(f"# {comment}\n")

    writer = csv.writer(buffer, lineterminator="\n")
    writer.writerow(INVENTORY_COLUMNS)
    for record in data["files"]:
        writer.writerow([
            record["relpath"],
            record["size"],
            record["modified"],
            record["sha256"],
            record["primary_class"],
            ";".join(record["secondary_classes"]),
            _yes_no(record["dispatch_related"]),
            record["text_confidence"],
            record["read_error"],
            ";".join(record["duplicate_of"]),
            ";".join(record["reasons"]),
        ])
    return buffer.getvalue()


def inventory_markdown(data: dict[str, Any]) -> str:
    lines = header_lines(data, "SANDBOX FILE INVENTORY")
    counts = data["counts"]
    lines += [
        "The authoritative machine-readable form of this inventory is the CSV emitted "
        "alongside it. This document is the human summary of the same data.",
        "",
    ]
    if not data["survey_performed"]:
        lines += _absent_section("Every file found")
        lines += _absent_section("Counts by class")
        return _render(lines + _footer(data))

    lines += [
        "## Totals",
        "",
        *_table(
            ("measure", "value"),
            [
                ("files inventoried", counts["files"]),
                ("folders walked", counts["directories"]),
                ("total bytes", f"{counts['total_bytes']:,}"),
                ("unreadable or not-followed entries", counts["unreadable"]),
                ("Dispatch-related", counts["dispatch_related"]),
                ("files with sensitive findings", counts["sensitive_files"]),
                ("prior output-folder files (excluded from the map)", counts["prior_output_files"]),
            ],
        ),
        "",
        "## Counts by primary class",
        "",
        *_table(
            ("class", "files"),
            [(name, value) for name, value in counts["by_primary_class"].items() if value],
        ),
        "",
        "## Every file",
        "",
        *_table(
            ("path", "size", "modified (UTC)", "sha256 (first 16)", "primary",
             "secondary", "Dispatch?"),
            [
                (
                    record["relpath"], f"{record['size']:,}", record["modified"] or "-",
                    (record["sha256"] or "-")[:16], record["primary_class"],
                    _classes(record), _yes_no(record["dispatch_related"]),
                )
                for record in data["files"]
            ],
        ),
        "",
    ]

    prior = data["prior_output_files"]
    lines += [
        "## Prior output-folder contents (reported separately, never overwritten)",
        "",
        "These files were already in the output folder before this run. They are **not** "
        "part of the Sandbox inventory, are **not** classified, and are **not** compared "
        "for duplication against Sandbox material — otherwise each run's reports would "
        "feed the next run's map. Output filenames are timestamped, so nothing here was "
        "replaced.",
        "",
        *_table(
            ("path (relative to output folder)", "size", "modified (UTC)", "sha256 (first 16)"),
            [
                (item["relpath"], f"{item['size']:,}", item["modified"] or "-",
                 (item["sha256"] or "-")[:16])
                for item in prior
            ],
        ),
        "",
    ]
    if data["notes"]:
        lines += ["## Notes", ""] + [f"- {note}" for note in data["notes"]] + [""]
    return _render(lines + _footer(data))


# --------------------------------------------------------------------------- 2. knowledge map

def knowledge_map(data: dict[str, Any]) -> str:
    lines = header_lines(data, "SANDBOX KNOWLEDGE MAP")
    lines += [
        "## Rules of interpretation used to build this map",
        "",
        "These are reproduced verbatim from the mission that commissioned the survey. "
        "Every classification in every document here was made under them.",
        "",
    ]
    lines += [f"{index}. {rule}" for index, rule in enumerate(data["interpretation_rules"], 1)]
    lines += [
        "",
        "## What this map is not",
        "",
        "- It is not an inventory of what is true about the business. It is an inventory "
        "of what is on a disk.",
        "- It does not accept anything it found as doctrine. Material that reads as "
        "doctrine is listed as a **candidate** in GOVERNANCE_AND_DOCTRINE_CANDIDATES.",
        "- It does not record any decision as made. Material that reads as a decision is "
        "listed as a **candidate** in MIKE_DECISION_CANDIDATES.",
        "- It quotes no file's contents anywhere.",
        "",
    ]
    if not data["survey_performed"]:
        lines += _absent_section("What exists")
        lines += _absent_section("How it relates")
        lines += _absent_section("What appears current versus superseded")
        lines += _absent_section("Unresolved questions found")
        lines += _absent_section("Prompt assets and reusable Company Library candidates")
        return _render(lines + _footer(data))

    counts = data["counts"]
    files = data["files"]
    dispatch_files = [record for record in files if record["dispatch_related"]]
    other_files = [record for record in files if not record["dispatch_related"]]
    superseded = [record for record in files
                  if record["superseded_markers"] or "Historical" in _all_classes(record)]
    # Membership by path rather than by dict equality: two files with identical
    # metadata are still two files, and `record not in superseded` would drop
    # the second one.
    superseded_paths = {record["relpath"] for record in superseded}
    current = [record for record in files if record["relpath"] not in superseded_paths]
    questions = [record for record in files if record["unresolved_question_markers"]]
    prompts = [record for record in files if record["prompt_asset"]]
    library = [record for record in files if record["library_candidate"]]
    unknowns = [record for record in files if record["primary_class"] == "Unknown"]

    lines += [
        "## What exists",
        "",
        f"The survey walked {counts['directories']} folders and inventoried "
        f"{counts['files']} files totalling {counts['total_bytes']:,} bytes. "
        f"{counts['unreadable']} entries could not be read, or were links that were "
        "deliberately not followed; every one of them is still in the inventory, "
        "classified `Unknown` with its reason recorded, because a silently dropped file "
        "is the one outcome that would make the inventory lie.",
        "",
        *_table(
            ("primary class", "files", "what that class means here"),
            [(name, value, _CLASS_MEANINGS[name])
             for name, value in counts["by_primary_class"].items() if value],
        ),
        "",
        "### Folders holding the most material",
        "",
        *_table(
            ("folder", "files", "bytes"),
            _top_folders(files),
        ),
        "",
        "## How it relates",
        "",
        f"{len(dispatch_files)} files carry at least one Dispatch signal — a programme "
        "name, a freight-operations term, or a contracting term matched as a whole word. "
        f"{len(other_files)} do not, and are non-Dispatch material for the purposes of "
        "this programme. Being non-Dispatch is not a judgement about a file's value; it "
        "means the file is out of scope for this survey's conclusions.",
        "",
        *_table(
            ("Dispatch signal", "files"),
            _signal_counts(dispatch_files),
        ),
        "",
        "## What appears current versus superseded",
        "",
        f"{len(current)} files carry no supersession signal. {len(superseded)} do — "
        "either a filename or path placing them in an old/archive/legacy context, or "
        "supersession language in the read sample. **This is a signal, not a verdict.** "
        "A file marked superseded here may be the only correct copy, and a file with no "
        "signal may be years out of date; nothing in a filesystem records which of two "
        "documents a person still believes.",
        "",
        *_table(
            ("path", "primary", "supersession markers", "last modified (UTC)"),
            [(record["relpath"], record["primary_class"], record["superseded_markers"],
              record["modified"] or "-")
             for record in sorted(superseded, key=lambda item: item["relpath"])],
        ),
        "",
        "## Unresolved questions found",
        "",
        f"{len(questions)} files contain markers of an open question (TODO, TBD, FIXME, "
        "'open question', 'needs a decision', and similar). The count of markers is "
        "reported; the text of the questions is not, because this document quotes no "
        "file content. The files themselves are where the questions are.",
        "",
        *_table(
            ("path", "open-question markers", "primary"),
            [(record["relpath"], record["unresolved_question_markers"], record["primary_class"])
             for record in sorted(questions, key=lambda item: -item["unresolved_question_markers"])],
        ),
        "",
        "## Prompt assets and reusable Company Library candidates",
        "",
        f"{len(prompts)} files look like prompt assets (a prompt/instruction filename, or "
        "system-prompt structure in the sample). "
        f"{len(library)} look like reusable Company Library candidates (templates, "
        "checklists, standard procedures, playbooks) that are not personal material.",
        "",
        *_table(
            ("path", "prompt asset", "library candidate", "primary"),
            [(record["relpath"], _yes_no(record["prompt_asset"]),
              _yes_no(record["library_candidate"]), record["primary_class"])
             for record in sorted(prompts + [item for item in library if not item["prompt_asset"]],
                                  key=lambda item: item["relpath"])],
        ),
        "",
        "## What the survey could not determine",
        "",
        f"{len(unknowns)} files are `Unknown`. That is the honest answer for each of them: "
        "either no rule matched, or the file could not be read, or it is a link that was "
        "not followed. None of these were promoted to a more useful-looking class to "
        "reduce this number.",
        "",
        *_table(
            ("path", "why Unknown"),
            [(record["relpath"], "; ".join(record["reasons"])[:200])
             for record in sorted(unknowns, key=lambda item: item["relpath"])],
        ),
        "",
    ]
    return _render(lines + _footer(data))


_CLASS_MEANINGS: dict[str, str] = {
    "Knowledge": "reference material: notes, guides, source, documentation",
    "Evidence": "an artefact produced by an event: exports, logs, images, receipts",
    "Research": "exploration of options; architecture research is NOT accepted architecture",
    "Decision": "an explicit human decision with an identifiable actor",
    "Doctrine": "matches doctrine already locked in this mission or the repository",
    "Draft": "unfinished or explicitly marked draft/WIP",
    "Duplicate": "byte-identical or near-identical to another file (see POSSIBLE_DUPLICATES)",
    "Historical": "sits in an old/archive/legacy context or reads as superseded",
    "Personal": "personal material, out of programme scope",
    "Sensitive": "a sensitive-material detector fired (see SENSITIVE_MATERIAL_REPORT)",
    "Unknown": "no rule matched, unreadable, or a link that was not followed",
}


def _all_classes(record: dict[str, Any]) -> list[str]:
    return [record["primary_class"], *record["secondary_classes"]]


def _top_folders(files: list[dict[str, Any]], limit: int = 25) -> list[tuple[Any, ...]]:
    folders: dict[str, list[int]] = {}
    for record in files:
        folder = record["relpath"].rsplit("/", 1)[0] if "/" in record["relpath"] else "(root)"
        bucket = folders.setdefault(folder, [0, 0])
        bucket[0] += 1
        bucket[1] += int(record["size"])
    ranked = sorted(folders.items(), key=lambda item: (-item[1][0], item[0]))
    return [(name, count, f"{size:,}") for name, (count, size) in ranked[:limit]]


def _signal_counts(files: list[dict[str, Any]]) -> list[tuple[Any, ...]]:
    tally: dict[str, int] = {}
    for record in files:
        for signal in record["dispatch_signals"]:
            tally[signal] = tally.get(signal, 0) + 1
    return [(name, count) for name, count in sorted(tally.items(), key=lambda item: (-item[1], item[0]))]


# --------------------------------------------------------------------------- 3. research candidates

def research_candidates(data: dict[str, Any]) -> str:
    lines = header_lines(data, "DISPATCH RESEARCH CANDIDATES")
    lines += [
        "Architecture and research material that carries at least one Dispatch signal. "
        "**Architecture research is not accepted architecture.** Everything listed here "
        "is material that may be worth reading before the next architecture decision; "
        "none of it is an architecture decision, and none of it has been adopted.",
        "",
    ]
    if not data["survey_performed"]:
        lines += _absent_section("Research candidates")
        return _render(lines + _footer(data))

    candidates = [
        record for record in data["files"]
        if record["dispatch_related"]
        and ("Research" in _all_classes(record) or "Knowledge" in _all_classes(record))
    ]
    candidates.sort(key=lambda record: (record["primary_class"], record["relpath"]))
    lines += [
        f"{len(candidates)} of {data['counts']['files']} inventoried files qualify.",
        "",
        *_table(
            ("path", "primary", "secondary", "why it is relevant to Dispatch",
             "why it was classed this way", "modified (UTC)"),
            [
                (
                    record["relpath"], record["primary_class"], _classes(record),
                    "signals: " + (", ".join(record["dispatch_signals"]) or "-"),
                    "; ".join(record["reasons"])[:220],
                    record["modified"] or "-",
                )
                for record in candidates
            ],
        ),
        "",
        "## AI-generated material within this set",
        "",
        "Flagged separately because **AI-generated reports are not human decisions**, and "
        "an AI-written architecture note reads exactly like a human-written one.",
        "",
        *_table(
            ("path", "primary"),
            [(record["relpath"], record["primary_class"])
             for record in candidates if record["ai_generated"]],
        ),
        "",
    ]
    return _render(lines + _footer(data))


# --------------------------------------------------------------------------- 4. duplicates

def possible_duplicates(data: dict[str, Any]) -> str:
    lines = header_lines(data, "POSSIBLE DUPLICATES")
    lines += [
        "Two independent signals were run: exact SHA-256 grouping, and near-content "
        "detection by normalised-token shingling plus normalised-name/size proximity. "
        "**Every group below carries the evidence for the match**, so a claim you "
        "disagree with can be checked against its own working rather than taken on trust.",
        "",
        "Nothing here proposes a deletion. Duplicate detection produces a *secondary* "
        "class and a numbered, reversible proposal in PROPOSED_ORGANIZATION_ACTIONS. "
        "This tool contains no code path that can move, rename, merge or delete a file.",
        "",
    ]
    if not data["survey_performed"]:
        lines += _absent_section("Exact duplicates")
        lines += _absent_section("Near duplicates")
        return _render(lines + _footer(data))

    duplicate_data = data["duplicates"]
    lines += ["## Exact duplicates (byte-identical)", ""]
    lines += _group_section(duplicate_data["exact"])
    lines += ["", "## Near duplicates", ""]
    lines += _group_section(duplicate_data["near"])
    if duplicate_data["notes"]:
        lines += ["", "## Gaps in this analysis", ""]
        lines += [f"- {note}" for note in duplicate_data["notes"]]
    lines += [""]
    return _render(lines + _footer(data))


def _group_section(groups: list[dict[str, Any]]) -> list[str]:
    if not groups:
        return ["_None found._"]
    lines: list[str] = []
    for index, group in enumerate(groups, 1):
        lines += [
            f"### Group {index} — signal `{group['signal']}`, score {group['score']}",
            "",
            f"**Evidence:** {group['evidence']}",
            "",
        ]
        lines += [f"- `{member}`" for member in group["members"]]
        lines.append("")
    return lines


# --------------------------------------------------------------------------- 5. doctrine

def governance_and_doctrine_candidates(data: dict[str, Any]) -> str:
    lines = header_lines(data, "GOVERNANCE AND DOCTRINE CANDIDATES")
    lines += [
        "**Notes are not doctrine.** Nothing in this document is doctrine. Material is "
        "listed here as a *candidate* because it reads like doctrine — imperative "
        "sentences, policy language, a governance filename — which is a fact about its "
        "prose style, not about its authority.",
        "",
        "`Doctrine` as a class was assigned only where a file matches doctrine already "
        "locked in this mission or in the DISPATCH repository. Those anchors are listed "
        "below so a reader can see exactly what 'matches' meant.",
        "",
        "## Locked doctrine anchors used for matching",
        "",
        *_table(
            ("anchor", "what it locks"),
            [(anchor["anchor_id"], anchor["title"]) for anchor in data["locked_doctrine"]],
        ),
        "",
    ]
    if not data["survey_performed"]:
        lines += _absent_section("Material matching locked doctrine")
        lines += _absent_section("Doctrine candidates")
        lines += _absent_section("Material conflicting with locked doctrine")
        return _render(lines + _footer(data))

    matching = [record for record in data["files"] if record["matches_locked_doctrine"]]
    candidates = [record for record in data["files"] if record["doctrine_candidate"]]
    conflicting = [record for record in data["files"] if record["conflicts_with_locked_doctrine"]]

    lines += [
        "## Material that matches locked doctrine",
        "",
        f"{len(matching)} files. A match means the file repeats enough of a locked "
        "anchor's language to be talking about the same rule. It does **not** mean the "
        "file is an authoritative statement of that rule; the repository and this mission "
        "remain the source of the locked text.",
        "",
        *_table(
            ("path", "anchors matched", "primary"),
            [(record["relpath"], ", ".join(record["matches_locked_doctrine"]),
              record["primary_class"])
             for record in sorted(matching, key=lambda item: item["relpath"])],
        ),
        "",
        "## Doctrine candidates (reads as doctrine; matches nothing locked)",
        "",
        f"{len(candidates)} files. Each needs Mike to say whether it is doctrine, was "
        "doctrine, or was never doctrine. Until he does, it is none of the three.",
        "",
        *_table(
            ("path", "primary", "secondary", "why it reads as doctrine", "modified (UTC)"),
            [(record["relpath"], record["primary_class"], _classes(record),
              "; ".join(record["reasons"])[:200], record["modified"] or "-")
             for record in sorted(candidates, key=lambda item: item["relpath"])],
        ),
        "",
        "## Material that conflicts with locked doctrine",
        "",
        f"{len(conflicting)} files. Two conflicts are detectable without quoting anything: "
        "a document grading readiness in status words outside the locked truth vocabulary "
        "(`TRUTH_VOCABULARY`), and a document carrying an attestation that a named person "
        "approved, verified, accepted, authorised or confirmed something "
        "(`NO_MANUFACTURED_ATTESTATION`). The second is not an accusation: it means the "
        "file asserts an authority that this survey may neither manufacture nor accept as "
        "proof. Only Mike can confirm or deny it, and the attestation text is deliberately "
        "not reproduced here.",
        "",
        *_table(
            ("path", "conflicts with", "attestation claims found"),
            [(record["relpath"], ", ".join(record["conflicts_with_locked_doctrine"]),
              record["attestation_claims"])
             for record in sorted(conflicting, key=lambda item: item["relpath"])],
        ),
        "",
    ]
    return _render(lines + _footer(data))


# --------------------------------------------------------------------------- 6. decisions

def mike_decision_candidates(data: dict[str, Any]) -> str:
    lines = header_lines(data, "MIKE DECISION CANDIDATES")
    lines += [
        "**A file is `Decision` only if it records an explicit human decision with an "
        "identifiable actor.** Everything else that mentions a decision is a *candidate* "
        "and appears in the second table below, not the first.",
        "",
        "**AI-generated reports are not human decisions.** A file that reads as "
        "AI-generated is never promoted to `Decision`, however decisive its prose.",
        "",
        "Nothing in this document is a decision Mike has made. It is a list of places "
        "where a decision appears to be recorded, or appears to be needed.",
        "",
    ]
    if not data["survey_performed"]:
        lines += _absent_section("Recorded decisions found")
        lines += _absent_section("Decision candidates")
        lines += _absent_section("Questions that appear to need Mike's decision")
        return _render(lines + _footer(data))

    recorded = [record for record in data["files"] if record["primary_class"] == "Decision"]
    candidates = [record for record in data["files"] if record["decision_candidate"]]
    questions = sorted(
        [record for record in data["files"] if record["unresolved_question_markers"]],
        key=lambda record: (-record["unresolved_question_markers"], record["relpath"]),
    )

    lines += [
        "## Recorded decisions found",
        "",
        f"{len(recorded)} files record what reads as an explicit decision by a named "
        "person. The name is **not** reproduced here — this document quotes no file "
        "content, and an attestation copied out of a Sandbox file is not evidence that "
        "the attestation is true. Open the file to see who and what.",
        "",
        *_table(
            ("path", "attestation claims in sample", "modified (UTC)", "secondary"),
            [(record["relpath"], record["attestation_claims"], record["modified"] or "-",
              _classes(record))
             for record in sorted(recorded, key=lambda item: item["relpath"])],
        ),
        "",
        "## Decision candidates (downgraded — no identifiable actor, or AI-generated)",
        "",
        f"{len(candidates)} files. Each carries decision language without an identifiable "
        "human actor, or reads as AI-generated. Each is a question for Mike: was this "
        "decided, by whom, and does it still hold?",
        "",
        *_table(
            ("path", "primary", "AI-generated?", "why it was downgraded", "modified (UTC)"),
            [(record["relpath"], record["primary_class"], _yes_no(record["ai_generated"]),
              "no identifiable actor in the read sample"
              if not record["ai_generated"]
              else "reads as AI-generated; an AI report is not a human decision",
              record["modified"] or "-")
             for record in sorted(candidates, key=lambda item: item["relpath"])],
        ),
        "",
        "## Questions that appear to need a decision",
        "",
        f"{len(questions)} files carry open-question markers. Marker counts only; the "
        "questions themselves stay in the files.",
        "",
        *_table(
            ("path", "open-question markers", "primary", "Dispatch-related"),
            [(record["relpath"], record["unresolved_question_markers"],
              record["primary_class"], _yes_no(record["dispatch_related"]))
             for record in questions],
        ),
        "",
        "## What this document does not do",
        "",
        "- It does not decide anything.",
        "- It does not record that Mike has seen it.",
        "- It does not treat any decision found in the Sandbox as still in force.",
        "",
    ]
    return _render(lines + _footer(data))


# --------------------------------------------------------------------------- 7. sensitive

def sensitive_material_report(data: dict[str, Any]) -> str:
    lines = header_lines(data, "SENSITIVE MATERIAL REPORT")
    lines += [
        "**Paths and categories only.** No matched string, no surrounding line, no "
        "excerpt and no sample of any file's contents appears in this document or in any "
        "other output of this tool. What is reported for each finding is: the path, the "
        "category, which detector fired, and how many times it fired. A count is metadata "
        "about content; it is not content.",
        "",
        "This is deliberate and structural. A sensitive-material report that quoted its "
        "evidence would be a second copy of every credential it found, in a document "
        "whose reassuring title guarantees it gets emailed and archived.",
        "",
        "Detectors are set to be eager. A false positive costs half a minute of looking at "
        "a file you wrote yourself; a false negative sends a credential into a "
        "reorganisation plan unflagged.",
        "",
    ]
    if not data["survey_performed"]:
        lines += _absent_section("Findings by category")
        lines += _absent_section("Findings by file")
        return _render(lines + _footer(data))

    findings = data["sensitive"]
    by_category: dict[str, list[dict[str, Any]]] = {}
    for finding in findings:
        by_category.setdefault(finding["category"], []).append(finding)

    lines += [
        "## Summary",
        "",
        *_table(
            ("category", "findings", "distinct files"),
            [(category, len(items), len({item["relpath"] for item in items}))
             for category, items in sorted(by_category.items())],
        ),
        "",
    ]
    for category in data["sensitive_categories"]:
        items = sorted(by_category.get(category, []), key=lambda item: (item["relpath"], item["detector"]))
        lines += [
            f"## {category}",
            "",
            *_table(
                ("path", "detector", "times detector fired"),
                [(item["relpath"], item["detector"], item["hits"]) for item in items],
            ),
            "",
        ]
    lines += [
        "## Handling",
        "",
        "- Nothing listed here has been copied, moved, quarantined or transmitted. The "
        "survey is read-only.",
        "- Nothing listed here should be committed to Git, pasted into a chat, or attached "
        "to an email until Mike has looked at the file himself.",
        "- Remediation is Mike's decision and is not proposed here.",
        "",
    ]
    return _render(lines + _footer(data))


# --------------------------------------------------------------------------- 8. folder structure

_STRUCTURE = (
    ("00_Inbox", "Anything not yet triaged. Empty is the goal, not the norm."),
    ("10_Research", "Exploration, options, comparisons, architecture research. "
                    "Research is not accepted architecture and never graduates by sitting here."),
    ("20_Knowledge", "Reference material that is true and reusable: notes, guides, glossaries."),
    ("30_Evidence", "Artefacts produced by an event: exports, logs, screenshots, receipts."),
    ("40_Decisions", "Only records of explicit human decisions with an identifiable actor. "
                     "A file enters this folder because Mike says so, never because a tool classified it."),
    ("50_Doctrine_Candidates", "Material that reads as doctrine. It stays a candidate until "
                               "Mike locks it. There is deliberately no folder named 'Doctrine'."),
    ("60_Drafts", "Unfinished work, explicitly marked as such."),
    ("70_Historical", "Superseded material kept for the record. Nothing is deleted to get here."),
    ("80_Personal", "Personal material. Out of programme scope; not surveyed for content again."),
    ("90_Sensitive", "Files a sensitive detector flagged. Access-restricted; never synced, "
                     "never committed."),
    ("95_Prompt_Assets", "Prompts and instruction sets, kept together because they are reused."),
    ("97_Company_Library_Candidates", "Templates, checklists and procedures that look reusable "
                                      "across the company, pending Mike's approval to promote."),
    ("99_Unknown", "Files no rule could classify. A real folder for a real answer."),
    ("Dispatch", "This tool's own outputs. Never reorganised, never inventoried into the map."),
)


def proposed_folder_structure(data: dict[str, Any]) -> str:
    lines = header_lines(data, "PROPOSED FOLDER STRUCTURE")
    lines += [
        "## The organising principle",
        "",
        "Three sources of truth, kept apart on purpose, because most of the confusion in "
        "a long-lived working folder comes from mixing them:",
        "",
        "1. **Repositories contain implementation truth.** What the software actually "
        "does is settled by the code and its tests, in Git — never by a document in a "
        "folder describing what it was meant to do.",
        "2. **Folders contain research and knowledge evidence.** This Sandbox holds the "
        "thinking, the exploration, the evidence and the record. It does not hold "
        "implementation truth, and a design document here never overrides the code.",
        "3. **Mike supplies operational truth and authority.** What is actually happening "
        "in the business, what has been decided, and what is doctrine — those come from "
        "Mike. No file and no tool can supply them, including this one.",
        "",
        "The structure below follows from that. It separates material by *what kind of "
        "truth it can carry*, rather than by topic, which is why there is a "
        "`50_Doctrine_Candidates` and deliberately no `Doctrine`.",
        "",
        "## Proposed structure",
        "",
        "```",
        f"{data['sandbox_root']}\\",
    ]
    for name, _ in _STRUCTURE:
        lines.append(f"  {name}\\")
    lines += [
        "```",
        "",
        *_table(("folder", "what belongs in it, and why"), list(_STRUCTURE)),
        "",
        "## Rules that come with the structure",
        "",
        "- Nothing is deleted to create it. Superseded material moves to `70_Historical`.",
        "- `40_Decisions` and any future `Doctrine` folder are populated by Mike, never by "
        "a classifier.",
        "- `Dispatch\\` is this tool's output folder and is excluded from every future "
        "survey's inventory, so the map never reads its own reports back in.",
        "- Implementation truth does not live here at all. If a document in this Sandbox "
        "and the repository disagree about what the software does, the repository is right "
        "and the document is Historical.",
        "",
    ]
    if not data["survey_performed"]:
        lines += _absent_section("Where the material found would go")
        return _render(lines + _footer(data))

    tally: dict[str, int] = {}
    for record in data["files"]:
        tally[record["primary_class"]] = tally.get(record["primary_class"], 0) + 1
    lines += [
        "## Where the material found would go",
        "",
        "Indicative only. Every actual move is a numbered proposal in "
        "PROPOSED_ORGANIZATION_ACTIONS awaiting Mike's separate approval.",
        "",
        *_table(
            ("primary class", "files", "proposed destination"),
            [(name, count, _DESTINATIONS[name]) for name, count in sorted(tally.items()) if count],
        ),
        "",
    ]
    return _render(lines + _footer(data))


_DESTINATIONS: dict[str, str] = {
    "Knowledge": "20_Knowledge",
    "Evidence": "30_Evidence",
    "Research": "10_Research",
    "Decision": "40_Decisions (only on Mike's confirmation)",
    "Doctrine": "50_Doctrine_Candidates (only Mike can promote past candidate)",
    "Draft": "60_Drafts",
    "Duplicate": "70_Historical (never deleted)",
    "Historical": "70_Historical",
    "Personal": "80_Personal",
    "Sensitive": "90_Sensitive",
    "Unknown": "99_Unknown",
}


# --------------------------------------------------------------------------- 9. actions

def proposed_organization_actions(data: dict[str, Any]) -> str:
    lines = header_lines(data, "PROPOSED ORGANIZATION ACTIONS")
    lines += [
        "> **NOTHING IN THIS DOCUMENT HAS BEEN EXECUTED, AND THIS TOOL CANNOT EXECUTE IT.**",
        ">",
        "> There is no code path in `dispatch.sandbox_survey` that performs a move, a "
        "rename, a merge or a deletion — not behind a flag, not behind a confirmation "
        "prompt, not at all. `tests/test_sandbox_survey.py` proves that by parsing the "
        "package's own source. Executing any action below is a separate decision by Mike, "
        "carried out by Mike, with tooling that does not yet exist.",
        "",
        "Every proposal is written to be reversible: a move records where the file came "
        "from, so undoing it is another move. No proposal deletes anything, merges file "
        "contents, or converts a file from one format to another.",
        "",
    ]
    if not data["survey_performed"]:
        lines += _absent_section("Proposed actions")
        lines += [
            "## Standing constraints on any future action list",
            "",
            *[f"{index}. {text}" for index, text in enumerate(_STANDING_CONSTRAINTS, 1)],
            "",
        ]
        return _render(lines + _footer(data))

    actions: list[tuple[str, str, str]] = []

    actions.append((
        f"Create the folder structure in PROPOSED_FOLDER_STRUCTURE under "
        f"`{data['sandbox_root']}`.",
        "No file moves. Creates empty folders only.",
        "Reversal: delete the empty folders.",
    ))

    tally: dict[str, list[str]] = {}
    for record in data["files"]:
        tally.setdefault(record["primary_class"], []).append(record["relpath"])
    for klass in sorted(tally):
        paths = sorted(tally[klass])
        actions.append((
            f"Move the {len(paths)} files classified `{klass}` to "
            f"`{_DESTINATIONS[klass]}`, preserving their relative subpaths.",
            f"Files: {len(paths)}. Full list is in the inventory CSV, column "
            f"`primary_class` = `{klass}`.",
            "Reversal: move each file back to the path recorded in the inventory CSV "
            "for this run.",
        ))

    exact_groups = data["duplicates"]["exact"]
    if exact_groups:
        actions.append((
            f"For each of the {len(exact_groups)} byte-identical groups in "
            "POSSIBLE_DUPLICATES, keep one copy in place and move the others to "
            "`70_Historical/duplicates/`.",
            "No deletion, no merge. The kept copy is Mike's choice, not the tool's; the "
            "tool states only that the files are byte-identical and gives the SHA-256.",
            "Reversal: move the copies back from `70_Historical/duplicates/`.",
        ))
    near_groups = data["duplicates"]["near"]
    if near_groups:
        actions.append((
            f"Review the {len(near_groups)} near-duplicate groups by hand before any "
            "of them is treated as a duplicate.",
            "Near-duplicate detection is a similarity signal with a stated score and "
            "stated evidence. It is not a finding of sameness, and no near-duplicate "
            "group should be collapsed on the strength of it alone.",
            "Reversal: none required; this is a reading task, not a change.",
        ))

    sensitive_paths = sorted({item["relpath"] for item in data["sensitive"]})
    if sensitive_paths:
        actions.append((
            f"Review the {len(sensitive_paths)} files listed in SENSITIVE_MATERIAL_REPORT "
            "and decide, per file, whether it should be moved to `90_Sensitive`, rotated "
            "and replaced, or left alone.",
            "The tool proposes no remediation. It does not know which credentials are "
            "live, which personal data is Mike's own, or which confidential material is "
            "held under an agreement that permits it.",
            "Reversal: any move is reversible via the inventory CSV.",
        ))

    candidates = sum(1 for record in data["files"] if record["doctrine_candidate"])
    if candidates:
        actions.append((
            f"Triage the {candidates} doctrine candidates in "
            "GOVERNANCE_AND_DOCTRINE_CANDIDATES: for each, Mike states whether it is "
            "doctrine, was doctrine, or was never doctrine.",
            "No file is promoted to doctrine by this tool under any circumstances. "
            "Notes are not doctrine.",
            "Reversal: none required; this produces a decision, not a change.",
        ))

    decisions = sum(1 for record in data["files"] if record["decision_candidate"])
    if decisions:
        actions.append((
            f"Triage the {decisions} decision candidates in MIKE_DECISION_CANDIDATES: "
            "for each, Mike states whether it was decided, by whom, and whether it holds.",
            "A file recording a decision is not proof the decision was made, and is "
            "certainly not proof it is still in force.",
            "Reversal: none required; this produces a decision, not a change.",
        ))

    lines += [
        "## Proposed actions",
        "",
        f"{len(actions)} proposals. Each awaits Mike's separate approval. None has run.",
        "",
    ]
    for index, (action, detail, reversal) in enumerate(actions, 1):
        lines += [
            f"### {index}. {action}",
            "",
            f"- **Detail:** {detail}",
            f"- **{reversal}**",
            "- **Status:** proposed — not executed, not approved, not scheduled.",
            "",
        ]
    lines += [
        "## Standing constraints on this action list",
        "",
        *[f"{index}. {text}" for index, text in enumerate(_STANDING_CONSTRAINTS, 1)],
        "",
    ]
    return _render(lines + _footer(data))


_STANDING_CONSTRAINTS: tuple[str, ...] = (
    "Nothing is executed by this tool. Executing any action is a separate Mike decision, "
    "performed with other tooling.",
    "Nothing is deleted. Ever. Superseded and duplicated material is moved, never removed.",
    "Nothing is merged and nothing is converted between formats.",
    "Every move is reversible from the inventory CSV of the run that proposed it.",
    "No file becomes doctrine, and no decision becomes a decision, by being moved into a "
    "folder with a confident name.",
    "The output folder is never reorganised by this list.",
)


# --------------------------------------------------------------------------- assembly

def survey_json(data: dict[str, Any]) -> str:
    return json.dumps(data, indent=2, sort_keys=False, ensure_ascii=False) + "\n"


# base name -> (extension, generator). The order here is the order the CLI
# reports them in, which is the order a reader should open them in.
DOCUMENTS: tuple[tuple[str, str, Callable[[dict[str, Any]], str]], ...] = (
    ("SANDBOX_FILE_INVENTORY", "csv", inventory_csv),
    ("SANDBOX_FILE_INVENTORY", "md", inventory_markdown),
    ("SANDBOX_KNOWLEDGE_MAP", "md", knowledge_map),
    ("DISPATCH_RESEARCH_CANDIDATES", "md", research_candidates),
    ("POSSIBLE_DUPLICATES", "md", possible_duplicates),
    ("GOVERNANCE_AND_DOCTRINE_CANDIDATES", "md", governance_and_doctrine_candidates),
    ("MIKE_DECISION_CANDIDATES", "md", mike_decision_candidates),
    ("SENSITIVE_MATERIAL_REPORT", "md", sensitive_material_report),
    ("PROPOSED_FOLDER_STRUCTURE", "md", proposed_folder_structure),
    ("PROPOSED_ORGANIZATION_ACTIONS", "md", proposed_organization_actions),
    ("sandbox_survey", "json", survey_json),
)


def generate_all(data: dict[str, Any]) -> list[tuple[str, str]]:
    """``[(filename, text)]`` for every document, filenames already timestamped.

    Timestamping is not cosmetic. It is what makes "never overwrite a prior
    output" achievable without the tool needing to reason about what is already
    in the folder: a run at a different second writes different names, and the
    writer opens with mode ``"x"`` so a collision refuses rather than replaces.
    """
    run_id = data["run_id"]
    return [
        (f"{base}_{run_id}.{extension}", generator(data))
        for base, extension, generator in DOCUMENTS
    ]
