"""Orchestration: scan, classify, deduplicate, detect — then hand over a dict.

The survey deliberately splits in two. `run_survey` produces a `SurveyResult`
and writes nothing at all; `write_reports` takes that result and a
`safety.OutputWriter` and produces files. Keeping them apart is what makes
``--dry-run`` honest rather than a flag that a future edit could quietly stop
respecting: in dry-run mode the writer is simply never given anything to do,
and there is no second code path that has to remember to check.

`SurveyResult.to_dict()` is the machine-readable truth, written out as
`sandbox_survey_<run-id>.json`. Every one of the nine Markdown and CSV documents
is generated by a pure function over that dict and nothing else -- no second
pass over the filesystem, no hidden state. Two consequences follow, and both are
worth the constraint: the JSON and the prose can never disagree, and the report
generators can be tested exhaustively against hand-written dicts without a
filesystem in sight.

ABSENT RESULTS ARE FIRST-CLASS. `absent_result` builds a well-formed result for
a survey that was *not performed*, which is how the template documents in
`proof/sandbox/` are produced -- by the same generators, from a result whose
status is the locked truth-vocabulary word ABSENT. The templates therefore
cannot drift out of shape from the real outputs, and they cannot accidentally
imply that anything was surveyed, because there is no file list in them to
imply it with.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from . import classifier, duplicates, scanner, sensitive
from .safety import OutputWriter, prepare_output_root, resolve_roots

TOOL_NAME = "dispatch.sandbox_survey"
TOOL_VERSION = "1.0.0"
GENERATED_BY = "Claude Code"

READ_ONLY_DECLARATION = "READ-ONLY PASS — NO FILES WERE MODIFIED"
AUTHORITY_DECLARATION = "Nothing in this report is accepted doctrine or a Mike decision."

# The locked truth vocabulary. `status` is always one of these words; no
# synonym is ever emitted anywhere in this package.
STATUS_COMPLETE = "MANUAL"      # a survey a human ran, by hand, on his own machine
STATUS_ABSENT = "ABSENT"        # the survey was not performed


@dataclass
class SurveyResult:
    """Everything the survey established, plus everything it declined to claim."""

    sandbox_root: str
    output_root: str
    generated_at: str
    run_id: str
    survey_performed: bool
    status: str
    max_bytes: int
    dry_run: bool = False
    absent_reason: str = ""
    files: list[dict[str, Any]] = field(default_factory=list)
    directories: list[str] = field(default_factory=list)
    prior_output_files: list[dict[str, Any]] = field(default_factory=list)
    duplicate_report: dict[str, Any] = field(default_factory=dict)
    sensitive_findings: list[dict[str, Any]] = field(default_factory=list)
    notes: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {
            "tool": TOOL_NAME,
            "tool_version": TOOL_VERSION,
            "generated_by": GENERATED_BY,
            "generated_at": self.generated_at,
            "run_id": self.run_id,
            "survey_performed": self.survey_performed,
            "status": self.status,
            "absent_reason": self.absent_reason,
            "sandbox_root": self.sandbox_root,
            "output_root": self.output_root,
            "dry_run": self.dry_run,
            "max_bytes": self.max_bytes,
            "read_only_declaration": READ_ONLY_DECLARATION,
            "authority_declaration": AUTHORITY_DECLARATION,
            "interpretation_rules": list(classifier.INTERPRETATION_RULES),
            "classes": list(classifier.CLASSES),
            "locked_doctrine": [
                {"anchor_id": anchor.anchor_id, "title": anchor.title}
                for anchor in classifier.LOCKED_DOCTRINE
            ],
            "sensitive_categories": list(sensitive.CATEGORIES),
            "counts": self.counts(),
            "files": self.files,
            "directories": self.directories,
            "prior_output_files": self.prior_output_files,
            "duplicates": self.duplicate_report or {"exact": [], "near": [], "notes": []},
            "sensitive": self.sensitive_findings,
            "notes": self.notes,
        }

    def counts(self) -> dict[str, Any]:
        by_class: dict[str, int] = {name: 0 for name in classifier.CLASSES}
        for record in self.files:
            by_class[record["primary_class"]] = by_class.get(record["primary_class"], 0) + 1
        duplicate_groups = self.duplicate_report or {}
        return {
            "files": len(self.files),
            "directories": len(self.directories),
            "total_bytes": sum(int(record["size"]) for record in self.files),
            "unreadable": sum(1 for record in self.files if record["read_error"]),
            "dispatch_related": sum(1 for record in self.files if record["dispatch_related"]),
            "decision_candidates": sum(1 for record in self.files if record["decision_candidate"]),
            "decisions": by_class.get("Decision", 0),
            "doctrine_candidates": sum(1 for record in self.files if record["doctrine_candidate"]),
            "doctrine": by_class.get("Doctrine", 0),
            "prompt_assets": sum(1 for record in self.files if record["prompt_asset"]),
            "library_candidates": sum(1 for record in self.files if record["library_candidate"]),
            "sensitive_files": len({item["relpath"] for item in self.sensitive_findings}),
            "prior_output_files": len(self.prior_output_files),
            "exact_duplicate_groups": len(duplicate_groups.get("exact", [])),
            "near_duplicate_groups": len(duplicate_groups.get("near", [])),
            "by_primary_class": by_class,
        }


def _now() -> datetime:
    return datetime.now(tz=timezone.utc)


def make_run_id(moment: datetime) -> str:
    """Compact UTC stamp used in every output filename.

    UTC rather than local time so two runs on the same machine sort correctly
    across a daylight-saving change, and so a run reproduced here is comparable
    with a run on Mike's machine without anyone having to reason about offsets.
    """
    return moment.strftime("%Y%m%dT%H%M%SZ")


def _file_record(
    scanned: scanner.ScannedFile,
    verdict: classifier.Classification,
    duplicate_of: list[str],
) -> dict[str, Any]:
    secondary = list(verdict.secondary)
    if duplicate_of and "Duplicate" not in secondary:
        secondary.append("Duplicate")
    return {
        "relpath": scanned.relpath,
        "absolute": scanned.absolute,
        "name": scanned.name,
        "suffix": scanned.suffix,
        "size": scanned.size,
        "modified": scanned.modified,
        "sha256": scanned.sha256,
        "is_symlink": scanned.is_symlink,
        "link_target_inside_root": scanned.link_target_inside_root,
        "read_error": scanned.read_error,
        "text_confidence": scanned.text_confidence,
        "sample_bytes": scanned.sample_bytes,
        "primary_class": verdict.primary,
        "secondary_classes": secondary,
        "reasons": list(verdict.reasons),
        "dispatch_related": verdict.dispatch_related,
        "dispatch_signals": list(verdict.dispatch_signals),
        "decision_candidate": verdict.decision_candidate,
        "doctrine_candidate": verdict.doctrine_candidate,
        "matches_locked_doctrine": list(verdict.matches_locked_doctrine),
        "conflicts_with_locked_doctrine": list(verdict.conflicts_with_locked_doctrine),
        "prompt_asset": verdict.prompt_asset,
        "library_candidate": verdict.library_candidate,
        "ai_generated": verdict.ai_generated,
        "content_evidence_used": verdict.content_evidence_used,
        "unresolved_question_markers": verdict.unresolved_question_markers,
        "superseded_markers": verdict.superseded_markers,
        "attestation_claims": verdict.attestation_claims,
        "duplicate_of": duplicate_of,
    }


def _group_dict(group: duplicates.DuplicateGroup) -> dict[str, Any]:
    return {
        "kind": group.kind,
        "signal": group.signal,
        "members": list(group.members),
        "evidence": group.evidence,
        "score": group.score,
    }


def run_survey(
    sandbox_root: Path | str,
    output_root: Path | str,
    *,
    max_bytes: int = scanner.DEFAULT_MAX_BYTES,
    dry_run: bool = False,
    moment: datetime | None = None,
) -> SurveyResult:
    """Read the Sandbox and build the result. Writes nothing to the input tree.

    The only filesystem mutation anywhere in this call is
    `prepare_output_root`, which creates the designated output folder and which
    is skipped entirely under `dry_run`.
    """
    resolved_input, resolved_output = resolve_roots(sandbox_root, output_root)
    prepare_output_root(resolved_output, dry_run=dry_run)

    scan = scanner.scan(resolved_input, resolved_output, max_bytes=max_bytes)
    duplicate_report = duplicates.find_duplicates(scan.files)

    membership: dict[str, list[str]] = {}
    for group in duplicate_report.all_groups:
        for member in group.members:
            others = [other for other in group.members if other != member]
            membership.setdefault(member, []).extend(others)

    sensitive_findings: list[dict[str, Any]] = []
    records: list[dict[str, Any]] = []
    for scanned in scan.files:
        verdict = classifier.classify(scanned)
        findings = sensitive.detect(scanned)
        record = _file_record(scanned, verdict, sorted(set(membership.get(scanned.relpath, []))))
        if findings:
            if "Sensitive" not in record["secondary_classes"]:
                record["secondary_classes"].append("Sensitive")
            sensitive_findings.extend(
                {
                    "relpath": finding.relpath,
                    "category": finding.category,
                    "detector": finding.detector,
                    "hits": finding.hits,
                }
                for finding in findings
            )
        records.append(record)

    moment = moment or _now()
    result = SurveyResult(
        sandbox_root=str(resolved_input),
        output_root=str(resolved_output),
        generated_at=moment.isoformat(timespec="seconds"),
        run_id=make_run_id(moment),
        survey_performed=True,
        status=STATUS_COMPLETE,
        max_bytes=max_bytes,
        dry_run=dry_run,
        files=records,
        directories=list(scan.directories),
        prior_output_files=[
            {
                "relpath": item.relpath,
                "size": item.size,
                "modified": item.modified,
                "sha256": item.sha256,
                "read_error": item.read_error,
            }
            for item in scan.prior_output_files
        ],
        duplicate_report={
            "exact": [_group_dict(group) for group in duplicate_report.exact],
            "near": [_group_dict(group) for group in duplicate_report.near],
            "notes": list(duplicate_report.notes),
        },
        sensitive_findings=sensitive_findings,
        notes=list(scan.notes),
    )
    if result.prior_output_files:
        result.notes.append(
            f"{len(result.prior_output_files)} files already existed in the output folder. "
            "They are listed separately as prior output-folder contents, are excluded from "
            "the Sandbox inventory and classification, and were not read into the map or "
            "overwritten."
        )
    return result


def absent_result(
    sandbox_root: str,
    output_root: str,
    *,
    reason: str,
    moment: datetime | None = None,
    max_bytes: int = scanner.DEFAULT_MAX_BYTES,
) -> SurveyResult:
    """A well-formed result for a survey that was NOT performed.

    Every content claim in the documents generated from this is the locked word
    ABSENT, and the reason is carried in the header of all nine of them. This is
    what the repository's template outputs are made from.
    """
    moment = moment or _now()
    return SurveyResult(
        sandbox_root=sandbox_root,
        output_root=output_root,
        generated_at=moment.isoformat(timespec="seconds"),
        run_id=make_run_id(moment),
        survey_performed=False,
        status=STATUS_ABSENT,
        max_bytes=max_bytes,
        absent_reason=reason,
    )


def write_reports(result: SurveyResult, writer: OutputWriter) -> list[Path]:
    """Render every document and hand each to the single permitted writer.

    Nothing here decides where a file goes; `OutputWriter.destination` does, and
    it refuses anything outside the output root. Under `--dry-run` the writer
    records the paths it would have created and creates none of them.
    """
    from . import reports

    data = result.to_dict()
    return [writer.emit(name, text) for name, text in reports.generate_all(data)]
