"""Proof that the Sandbox survey is read-only, non-executing and non-leaking.

The survey tool exists to be pointed at somebody else's long-lived working
folder. Its entire value is a set of promises about what it does *not* do, so
these tests are written the way you would write them if you had to hand the
result to the folder's owner:

* `test_input_tree_is_byte_identical_after_a_full_run` records every input
  file's size, mtime and SHA-256 plus the complete directory listing before the
  run, and asserts afterwards that nothing changed and that the only new paths
  are inside the designated output folder.
* `test_no_move_rename_or_merge_code_path_exists` and its neighbours parse the
  package's own source. A promise enforced by documentation is a promise that
  survives exactly until the next refactor; a promise enforced by an AST walk
  fails the build.
* `test_a_fabricated_credential_never_reaches_any_output` puts a fake secret in
  the input tree and asserts the string appears in none of the eleven files
  written.

Nothing here runs against the real Sandbox. `D:\\Sandbox\\Play Pen` does not
exist in this environment and is never touched; every test builds its own tree
under `tmp_path`.
"""

from __future__ import annotations

import ast
import csv
import io
import os
from datetime import datetime, timezone
from pathlib import Path

import pytest

from dispatch.sandbox_survey import (
    classifier,
    duplicates,
    reports,
    safety,
    scanner,
    sensitive,
    survey,
)

import scripts.sandbox_survey as cli  # noqa: E402

MOMENT = datetime(2026, 8, 24, 13, 14, 15, tzinfo=timezone.utc)
RUN_ID = "20260824T131415Z"

# A fabricated credential. It is not a real key and never was; it exists only so
# that a test can assert it never reaches an output file.
FAKE_SECRET = "sk-sandboxsurveyfake-9Q7HXH2PL4TZ0RVK"
FAKE_AWS_KEY = "AKIAQ7HXH2PL4TZ0RVKM"


# --------------------------------------------------------------------------- fixtures

def _write(path: Path, text: str) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return path


@pytest.fixture
def sandbox(tmp_path: Path) -> Path:
    """A small stand-in for a real working folder, exercising every rule path."""
    root = tmp_path / "Play Pen"
    _write(root / "research" / "routing_architecture_options.md",
           "# Routing architecture research\n\n"
           "We could use option A or option B for the Dispatch load board. "
           "Trade-offs matter here. TODO: decide later. FIXME as well.\n"
           "Freight lane and broker considerations follow.\n")
    _write(root / "research" / "routing_architecture_options - Copy.md",
           "# Routing architecture research\n\n"
           "We could use option A or option B for the Dispatch load board. "
           "Trade-offs matter here. TODO: decide later. FIXME as well.\n"
           "Freight lane and broker considerations follow, with one extra line.\n")
    _write(root / "notes" / "meeting_notes.md",
           "Overview of how to run the weekly dispatcher sync. Steps: one, two.\n")
    _write(root / "decisions" / "lane_template_decision.md",
           "Decision: we will adopt lane templates for the carrier portal.\n"
           "Approved by Dana Fixture on 2026-01-02.\n")
    _write(root / "notes" / "ai_summary.md",
           "Certainly! Here is a summary. We decided to move the driver portal. "
           "Generated by ChatGPT for the Dispatch programme.\n")
    _write(root / "governance" / "operating_policy.md",
           "Policy: contributors must not commit a secret or a credential.\n"
           "Never commit runtime logs.\n")
    _write(root / "governance" / "readiness_board.md",
           "Doctrine: the board must not lie.\nStatus: READY. Delivery is DONE.\n")
    _write(root / "personal" / "tax_return_2024.txt",
           "Personal tax paperwork. Account number: 12345678\n")
    _write(root / "secrets" / "deploy_notes.txt",
           f"api_key = {FAKE_SECRET}\n{FAKE_AWS_KEY}\ncontact: fixture@example.invalid\n")
    _write(root / "old" / "routing_notes.md",
           "This approach is deprecated and has been superseded. Old version.\n")
    (root / "binary" ).mkdir(parents=True, exist_ok=True)
    (root / "binary" / "payload.dat").write_bytes(b"\x00\x01\x02\x03" * 64)
    (root / "binary" / "mojibake.txt").write_bytes(b"caf\xe9 na\xefve summary\n")
    return root


@pytest.fixture
def output_root(sandbox: Path) -> Path:
    return sandbox / "Dispatch"


def _run(sandbox: Path, output_root: Path, **kwargs) -> survey.SurveyResult:
    kwargs.setdefault("moment", MOMENT)
    return survey.run_survey(sandbox, output_root, **kwargs)


def _write_all(result: survey.SurveyResult, output_root: Path) -> list[Path]:
    writer = safety.OutputWriter(output_root=Path(result.output_root))
    return survey.write_reports(result, writer)


def _snapshot(root: Path) -> dict[str, tuple]:
    """Every path under `root`, with the facts a write would disturb."""
    seen: dict[str, tuple] = {}
    for dirpath, dirnames, filenames in os.walk(root, followlinks=False):
        here = Path(dirpath)
        seen[str(here.relative_to(root))] = ("dir",)
        for name in dirnames + filenames:
            item = here / name
            rel = str(item.relative_to(root))
            if item.is_symlink():
                seen[rel] = ("link", os.readlink(item))
                continue
            if item.is_dir():
                seen[rel] = ("dir",)
                continue
            stat = item.stat()
            from dispatch.backup import sha256_file
            seen[rel] = ("file", stat.st_size, stat.st_mtime_ns, sha256_file(item))
    return seen


# --------------------------------------------------------------------------- the read-only proof

def test_input_tree_is_byte_identical_after_a_full_run(sandbox: Path, output_root: Path):
    """The headline guarantee: a full run changes nothing it read."""
    before = _snapshot(sandbox)
    assert not any(key.startswith("Dispatch") for key in before)

    result = _run(sandbox, output_root)
    written = _write_all(result, output_root)
    assert written

    after = _snapshot(sandbox)

    # Every path that existed before still exists, unchanged in size, mtime and
    # content hash. mtime at nanosecond resolution catches a rewrite that
    # happened to reproduce the same bytes.
    for rel, facts in before.items():
        assert rel in after, f"{rel} disappeared during a read-only pass"
        assert after[rel] == facts, f"{rel} was modified during a read-only pass"

    # The only new paths are inside the designated output folder.
    new_paths = set(after) - set(before)
    assert new_paths
    for rel in new_paths:
        assert rel == "Dispatch" or rel.startswith("Dispatch" + os.sep), (
            f"{rel} was created outside the designated output folder"
        )


def test_dry_run_creates_nothing_at_all(sandbox: Path, output_root: Path):
    before = _snapshot(sandbox)
    result = _run(sandbox, output_root, dry_run=True)
    writer = safety.OutputWriter(output_root=output_root, dry_run=True)
    planned = survey.write_reports(result, writer)

    assert len(planned) == len(reports.DOCUMENTS)
    assert not output_root.exists()
    assert _snapshot(sandbox) == before


def test_no_move_rename_or_merge_code_path_exists():
    """Parse the package. There is no such code path, behind a flag or otherwise."""
    mutating_methods = {
        "unlink", "rmdir", "write_text", "write_bytes", "touch", "chmod",
        "lchmod", "symlink_to", "hardlink_to", "rename", "rmtree", "move",
        "copytree", "copyfile", "truncate",
    }
    mutating_os = {
        "rename", "replace", "remove", "unlink", "rmdir", "removedirs", "chmod",
        "chown", "utime", "truncate", "link", "symlink", "system", "popen",
        "open", "makedirs", "mkdir", "write",
    }
    for path, tree in _package_sources():
        for node in ast.walk(tree):
            if not isinstance(node, ast.Call):
                continue
            dotted = _dotted(node.func)
            if dotted.startswith("os."):
                assert dotted.split(".")[-1] not in mutating_os, f"{path.name}: {dotted}"
            if isinstance(node.func, ast.Attribute):
                assert node.func.attr not in mutating_methods, (
                    f"{path.name}: calls {node.func.attr}()"
                )


def test_the_only_input_file_mode_is_rb():
    """`open()` takes mode "rb" everywhere except the one write choke-point."""
    seen_write = 0
    for path, tree in _package_sources():
        for node in ast.walk(tree):
            if not isinstance(node, ast.Call) or _dotted(node.func) != "open":
                continue
            assert len(node.args) >= 2, f"{path.name}: open() with no explicit mode"
            mode = node.args[1]
            assert isinstance(mode, ast.Constant), f"{path.name}: non-literal open() mode"
            if path.name == "safety.py":
                assert mode.value == "x", f"safety.py: unexpected write mode {mode.value!r}"
                seen_write += 1
            else:
                assert mode.value == "rb", f"{path.name}: open() mode {mode.value!r}"
    assert seen_write == 1, "there must be exactly one write call in the whole package"


def test_mkdir_happens_only_in_the_safety_choke_point():
    for path, tree in _package_sources():
        for node in ast.walk(tree):
            if isinstance(node, ast.Call) and isinstance(node.func, ast.Attribute):
                if node.func.attr == "mkdir":
                    assert path.name == "safety.py", f"{path.name} creates directories"


def test_no_network_or_execution_capability_is_imported():
    forbidden = {
        "subprocess", "socket", "urllib", "http", "requests", "ftplib", "smtplib",
        "telnetlib", "runpy", "importlib", "ctypes", "pickle", "multiprocessing",
        "asyncio", "webbrowser", "shutil", "tempfile", "ssl", "xmlrpc",
    }
    for path, tree in _package_sources():
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                for alias in node.names:
                    assert alias.name.split(".")[0] not in forbidden, f"{path.name}: {alias.name}"
            elif isinstance(node, ast.ImportFrom) and node.module:
                assert node.module.split(".")[0] not in forbidden, f"{path.name}: {node.module}"
            elif isinstance(node, ast.Call) and _dotted(node.func) in {
                "exec", "eval", "compile", "__import__"
            }:
                pytest.fail(f"{path.name}: {_dotted(node.func)}() is an execution primitive")


def test_a_script_in_the_input_tree_is_never_executed(sandbox: Path, output_root: Path, tmp_path: Path):
    """A .py and a .sh in the tree get read as bytes and nothing more."""
    sentinel = tmp_path / "SENTINEL_SHOULD_NOT_EXIST"
    _write(sandbox / "tools" / "helper.py",
           f"from pathlib import Path\nPath({str(sentinel)!r}).write_text('executed')\n")
    _write(sandbox / "tools" / "helper.sh",
           f"#!/bin/sh\necho executed > {sentinel}\n")

    result = _run(sandbox, output_root)
    _write_all(result, output_root)

    assert not sentinel.exists(), "a file found in the Sandbox was executed"
    paths = {record["relpath"] for record in result.files}
    assert "tools/helper.py" in paths and "tools/helper.sh" in paths


def test_no_socket_is_opened_during_a_run(sandbox: Path, output_root: Path, monkeypatch):
    import socket

    def _refuse(*args, **kwargs):  # pragma: no cover - fires only on a regression
        pytest.fail("the survey opened a network connection")

    monkeypatch.setattr(socket, "socket", _refuse)
    monkeypatch.setattr(socket, "create_connection", _refuse)
    result = _run(sandbox, output_root)
    _write_all(result, output_root)
    assert result.files


def _package_sources() -> list[tuple[Path, ast.Module]]:
    package = Path(survey.__file__).parent
    files = sorted(package.glob("*.py")) + [Path(cli.__file__)]
    return [(path, ast.parse(path.read_text(encoding="utf-8"))) for path in files]


def _dotted(node: ast.expr) -> str:
    parts: list[str] = []
    while isinstance(node, ast.Attribute):
        parts.append(node.attr)
        node = node.value
    if isinstance(node, ast.Name):
        parts.append(node.id)
    return ".".join(reversed(parts))


# --------------------------------------------------------------------------- output-root handling

def test_output_root_is_excluded_from_the_inventory(sandbox: Path, output_root: Path):
    first = _run(sandbox, output_root)
    _write_all(first, output_root)

    second = survey.run_survey(
        sandbox, output_root, moment=datetime(2026, 8, 24, 14, 0, 0, tzinfo=timezone.utc)
    )
    inventoried = {record["relpath"] for record in second.files}
    assert not any(rel.startswith("Dispatch/") for rel in inventoried)
    assert not any(rel.startswith("Dispatch") for rel in second.directories)


def test_a_folder_merely_named_dispatch_elsewhere_is_still_inventoried(sandbox: Path, output_root: Path):
    """Pruning is by resolved path, not by name."""
    _write(sandbox / "research" / "Dispatch" / "decoy.md", "notes about something\n")
    result = _run(sandbox, output_root)
    assert "research/Dispatch/decoy.md" in {record["relpath"] for record in result.files}


def test_prior_output_contents_are_reported_separately_and_not_overwritten(
    sandbox: Path, output_root: Path
):
    first = _run(sandbox, output_root)
    first_written = _write_all(first, output_root)
    fingerprints = {path: path.read_bytes() for path in first_written}

    second = survey.run_survey(
        sandbox, output_root, moment=datetime(2026, 8, 24, 14, 0, 0, tzinfo=timezone.utc)
    )
    second_written = _write_all(second, output_root)

    prior = {item["relpath"] for item in second.prior_output_files}
    assert prior == {path.name for path in first_written}
    assert not any(item["relpath"] in prior for item in second.sensitive_findings)

    for path, content in fingerprints.items():
        assert path.exists() and path.read_bytes() == content, "a prior output was overwritten"
    assert set(second_written).isdisjoint(set(first_written))
    assert any("prior output-folder contents" in note for note in second.notes)


def test_output_filenames_are_timestamped(sandbox: Path, output_root: Path):
    result = _run(sandbox, output_root)
    written = _write_all(result, output_root)
    names = [path.name for path in written]
    assert len(names) == len(reports.DOCUMENTS)
    for name in names:
        assert RUN_ID in name, name
    assert f"SANDBOX_FILE_INVENTORY_{RUN_ID}.csv" in names
    assert f"SANDBOX_FILE_INVENTORY_{RUN_ID}.md" in names
    assert f"PROPOSED_ORGANIZATION_ACTIONS_{RUN_ID}.md" in names
    assert f"sandbox_survey_{RUN_ID}.json" in names


# --------------------------------------------------------------------------- the writer choke-point

def test_writer_refuses_a_destination_outside_the_output_root(tmp_path: Path):
    root = tmp_path / "out"
    root.mkdir()
    writer = safety.OutputWriter(output_root=root)

    for name in ("../escape.md", "a/../../escape.md", str(tmp_path / "absolute.md"), "."):
        with pytest.raises(safety.SandboxSafetyError):
            writer.destination(name)
    assert not (tmp_path / "escape.md").exists()
    assert not (tmp_path / "absolute.md").exists()


def test_writer_refuses_a_destination_that_escapes_through_a_link(tmp_path: Path):
    """The containment check resolves the path, so a symlinked subfolder cannot
    smuggle a write out of the output root."""
    root = tmp_path / "out"
    root.mkdir()
    outside = tmp_path / "outside"
    outside.mkdir()
    (root / "link").symlink_to(outside, target_is_directory=True)
    writer = safety.OutputWriter(output_root=root)
    with pytest.raises(safety.SandboxSafetyError, match="outside the designated output folder"):
        writer.destination("link/report.md")
    assert not (outside / "report.md").exists()


def test_writer_refuses_to_overwrite(tmp_path: Path):
    root = tmp_path / "out"
    root.mkdir()
    writer = safety.OutputWriter(output_root=root)
    writer.emit("report.md", "first")
    with pytest.raises(safety.SandboxSafetyError):
        writer.emit("report.md", "second")
    assert (root / "report.md").read_text(encoding="utf-8") == "first"


def test_writer_dry_run_records_but_writes_nothing(tmp_path: Path):
    root = tmp_path / "out"
    root.mkdir()
    writer = safety.OutputWriter(output_root=root, dry_run=True)
    target = writer.emit("report.md", "content")
    assert writer.written == [target]
    assert not target.exists()


def test_writer_creates_the_file_under_the_root(tmp_path: Path):
    root = tmp_path / "out"
    root.mkdir()
    writer = safety.OutputWriter(output_root=root)
    target = writer.emit("SANDBOX_FILE_INVENTORY_20260824T131415Z.md", "content")
    assert target.parent == root
    assert target.read_text(encoding="utf-8") == "content"

    # A nested name resolves inside the root, but the writer does not create
    # directories -- only `prepare_output_root` may, and only the output root.
    # The refusal therefore comes from the OS, not from a silent mkdir.
    nested = writer.destination("nested/report.md")
    assert safety.is_within(nested, root)
    with pytest.raises(FileNotFoundError):
        writer.emit("nested/report.md", "content")
    assert not (root / "nested").exists()


# --------------------------------------------------------------------------- root refusals

def test_refuses_an_output_root_outside_the_input_root(tmp_path: Path):
    inside = tmp_path / "Play Pen"
    inside.mkdir()
    outside = tmp_path / "Elsewhere"
    with pytest.raises(safety.SandboxSafetyError, match="must be inside"):
        safety.resolve_roots(inside, outside)


def test_refuses_an_output_root_equal_to_the_input_root(tmp_path: Path):
    inside = tmp_path / "Play Pen"
    inside.mkdir()
    with pytest.raises(safety.SandboxSafetyError, match="may not be the Sandbox folder"):
        safety.resolve_roots(inside, inside)


def test_refuses_a_missing_or_non_directory_sandbox(tmp_path: Path):
    with pytest.raises(safety.SandboxSafetyError, match="does not exist"):
        safety.resolve_roots(tmp_path / "nope", tmp_path / "nope" / "Dispatch")
    file_root = tmp_path / "a-file.txt"
    file_root.write_text("x", encoding="utf-8")
    with pytest.raises(safety.SandboxSafetyError, match="not a folder"):
        safety.resolve_roots(file_root, file_root / "Dispatch")


def test_refuses_an_output_path_that_is_a_file(tmp_path: Path):
    root = tmp_path / "Play Pen"
    root.mkdir()
    collision = root / "Dispatch"
    collision.write_text("not a folder", encoding="utf-8")
    with pytest.raises(safety.SandboxSafetyError, match="not a folder"):
        safety.resolve_roots(root, collision)


def test_refuses_when_the_output_root_cannot_be_created(tmp_path: Path, monkeypatch):
    root = tmp_path / "Play Pen"
    root.mkdir()
    target = root / "Dispatch"

    def _boom(*args, **kwargs):
        raise PermissionError("read-only volume")

    monkeypatch.setattr(Path, "mkdir", _boom)
    with pytest.raises(safety.SandboxSafetyError, match="could not be created"):
        safety.prepare_output_root(target, dry_run=False)
    # Under dry-run even the one permitted structural change is skipped.
    safety.prepare_output_root(target, dry_run=True)


def test_is_within_and_long_path():
    root = Path("/a/b")
    assert safety.is_within(root, root)
    assert safety.is_within(Path("/a/b/c"), root)
    assert not safety.is_within(Path("/a/x"), root)

    short = Path("/a/b")
    assert safety.long_path(short, windows=False) == "/a/b"
    assert safety.long_path(short, windows=True) == "/a/b"

    long_drive = Path("C:\\" + "x" * 300)
    assert safety.long_path(long_drive, windows=True).startswith("\\\\?\\C:")
    assert safety.long_path(long_drive, windows=False) == str(long_drive)

    unc = Path("\\\\server\\share\\" + "y" * 300)
    assert safety.long_path(unc, windows=True).startswith("\\\\?\\UNC")

    already = Path("\\\\?\\C:\\" + "z" * 300)
    assert safety.long_path(already, windows=True) == str(already)
    assert isinstance(safety.on_windows(), bool)


# --------------------------------------------------------------------------- symlinks

def test_a_symlink_out_of_the_root_is_recorded_but_never_followed(
    sandbox: Path, output_root: Path, tmp_path: Path
):
    secret_outside = tmp_path / "outside" / "not_ours.txt"
    _write(secret_outside, "content that must never be read\n")
    (sandbox / "escape_link").symlink_to(secret_outside)
    (sandbox / "internal_link").symlink_to(sandbox / "notes" / "meeting_notes.md")

    result = _run(sandbox, output_root)
    by_path = {record["relpath"]: record for record in result.files}

    escaping = by_path["escape_link"]
    assert escaping["is_symlink"] and escaping["link_target_inside_root"] is False
    assert escaping["primary_class"] == "Unknown"
    assert escaping["sha256"] == ""
    assert "OUTSIDE" in escaping["read_error"]

    internal = by_path["internal_link"]
    assert internal["link_target_inside_root"] is True
    assert internal["sha256"] == ""

    # Nothing outside the root was hashed, so its content cannot have been read.
    assert "not_ours" not in "".join(record["relpath"] for record in result.files)


def test_a_symlinked_directory_is_not_descended(sandbox: Path, output_root: Path, tmp_path: Path):
    outside_dir = tmp_path / "outside_tree"
    _write(outside_dir / "hidden.md", "must not appear\n")
    (sandbox / "linked_dir").symlink_to(outside_dir, target_is_directory=True)

    result = _run(sandbox, output_root)
    paths = {record["relpath"] for record in result.files}
    assert not any("hidden.md" in path for path in paths)


# --------------------------------------------------------------------------- scanner details

def test_unreadable_files_are_inventoried_not_skipped(sandbox: Path, output_root: Path, monkeypatch):
    real = scanner.sha256_file
    target = "notes/meeting_notes.md"

    def _selective(path: Path):
        if path.name == "meeting_notes.md":
            raise PermissionError("access is denied")
        return real(path)

    monkeypatch.setattr(scanner, "sha256_file", _selective)
    result = _run(sandbox, output_root)
    record = next(item for item in result.files if item["relpath"] == target)
    assert record["primary_class"] == "Unknown"
    assert "PermissionError" in record["read_error"]
    assert record["text_confidence"] == "unread"
    assert result.counts()["unreadable"] >= 1


def test_undecodable_bytes_do_not_crash_the_scan(sandbox: Path, output_root: Path):
    (sandbox / "binary" / "undecodable.txt").write_bytes(b"\x81\x8d\x8f\x90\x9d")
    result = _run(sandbox, output_root)
    record = next(item for item in result.files if item["relpath"] == "binary/undecodable.txt")
    assert record["text_confidence"] in ("lossy", "binary")


def test_decode_paths():
    assert scanner._decode(b"plain text") == ("plain text", "text")
    text, confidence = scanner._decode(b"caf\xe9")
    assert confidence == "lossy" and "caf" in text
    assert scanner._decode(b"\x00\x01binary")[1] == "binary"
    assert scanner._decode(b"\x81\x8d\x8f")[1] == "lossy"


def test_a_file_whose_metadata_cannot_be_read_is_still_inventoried(
    sandbox: Path, output_root: Path, monkeypatch
):
    real_stat = Path.stat

    def _selective(self, *args, **kwargs):
        if self.name == "meeting_notes.md":
            raise PermissionError("stat denied")
        return real_stat(self, *args, **kwargs)

    monkeypatch.setattr(Path, "stat", _selective)
    result = _run(sandbox, output_root)
    record = next(item for item in result.files if item["relpath"] == "notes/meeting_notes.md")
    assert record["primary_class"] == "Unknown"
    assert record["size"] == 0 and record["sha256"] == ""
    assert "PermissionError" in record["read_error"]


def test_a_link_whose_target_cannot_be_resolved_is_treated_as_escaping(
    sandbox: Path, output_root: Path, monkeypatch
):
    """Fail closed: a link we cannot resolve is reported as pointing outside."""
    (sandbox / "odd_link").symlink_to(sandbox / "notes" / "meeting_notes.md")
    real_resolve = Path.resolve

    def _selective(self, *args, **kwargs):
        if self.name == "odd_link":
            raise OSError("too many levels of symbolic links")
        return real_resolve(self, *args, **kwargs)

    monkeypatch.setattr(Path, "resolve", _selective)
    result = _run(sandbox, output_root)
    record = next(item for item in result.files if item["relpath"] == "odd_link")
    assert record["link_target_inside_root"] is False
    assert "OUTSIDE" in record["read_error"]


def test_safe_lstat_reports_an_error_instead_of_raising(tmp_path: Path):
    size, modified, error = scanner.safe_lstat(tmp_path / "nothing-here")
    assert (size, modified) == (0, "")
    assert "FileNotFoundError" in error


def test_unknown_extension_that_decodes_cleanly_is_judged_on_printability(
    sandbox: Path, output_root: Path
):
    _write(sandbox / "odd" / "prose.weirdext", "This is ordinary readable prose.\n")
    (sandbox / "odd" / "noise.weirdext").write_bytes(b"\x01\x02\x03\x04\x05\x06\x07\x08")
    result = _run(sandbox, output_root)
    by_path = {record["relpath"]: record for record in result.files}
    assert by_path["odd/prose.weirdext"]["text_confidence"] == "text"
    assert by_path["odd/noise.weirdext"]["text_confidence"] == "binary"
    assert not scanner._looks_like_prose("")


def test_max_bytes_caps_the_heuristic_read(sandbox: Path, output_root: Path):
    result = _run(sandbox, output_root, max_bytes=8)
    for record in result.files:
        assert record["sample_bytes"] <= 8
    # The hash is still over the whole file, not the sample.
    notes = next(item for item in result.files if item["relpath"] == "notes/meeting_notes.md")
    assert len(notes["sha256"]) == 64


# --------------------------------------------------------------------------- classification

def _classify_text(name: str, body: str, **kwargs) -> classifier.Classification:
    scanned = scanner.ScannedFile(
        relpath=name, absolute="/tmp/" + name, name=name.rsplit("/", 1)[-1],
        suffix="." + name.rsplit(".", 1)[-1] if "." in name else "",
        size=len(body), modified="2026-01-01T00:00:00+00:00", sha256="0" * 64,
        sample=body, sample_bytes=len(body), **kwargs,
    )
    return classifier.classify(scanned)


def test_a_decision_needs_an_identifiable_actor():
    with_actor = _classify_text(
        "decisions/lane.md",
        "Decision: we will adopt lane templates.\nApproved by Dana Fixture.\n")
    assert with_actor.primary == "Decision"
    assert with_actor.decision_candidate is False
    assert with_actor.attestation_claims == 1

    without_actor = _classify_text(
        "decisions/lane.md", "Decision: we will adopt lane templates. Approved by the team.\n")
    assert without_actor.primary != "Decision"
    assert "Decision" not in without_actor.all_classes
    assert without_actor.decision_candidate is True


def test_an_ai_generated_report_is_never_a_decision():
    verdict = _classify_text(
        "notes/summary.md",
        "Certainly! Here is the summary. We decided to adopt it. "
        "Approved by Dana Fixture. Generated by ChatGPT.\n")
    assert verdict.ai_generated is True
    assert verdict.primary != "Decision"
    assert verdict.decision_candidate is True
    assert "Research<-ai.generated_report_is_not_a_human_decision" in verdict.reasons


def test_doctrine_requires_a_match_against_locked_doctrine():
    lookalike = _classify_text(
        "governance/house_rules.md",
        "Doctrine: contributors must not argue in the pull request.\n")
    assert lookalike.primary != "Doctrine"
    assert "Doctrine" not in lookalike.all_classes
    assert lookalike.doctrine_candidate is True
    assert lookalike.matches_locked_doctrine == ()

    matching = _classify_text(
        "governance/secrets.md",
        "Policy: do not commit a secret. Never commit a credential of any kind.\n")
    assert matching.primary == "Doctrine"
    assert "NO_SECRETS_IN_GIT" in matching.matches_locked_doctrine
    assert matching.doctrine_candidate is False


def test_locked_doctrine_matching_and_conflicts():
    vocabulary = "LIVE CONFIGURED UNCONFIGURED SIMULATED".lower()
    assert "TRUTH_VOCABULARY" in classifier.locked_doctrine_matches(vocabulary)
    assert classifier.locked_doctrine_matches("nothing in particular") == ()

    assert classifier.locked_doctrine_conflicts("Status: READY", 0) == ("TRUTH_VOCABULARY",)
    assert classifier.locked_doctrine_conflicts("plain prose", 2) == (
        "NO_MANUFACTURED_ATTESTATION",)
    assert classifier.locked_doctrine_conflicts("ALREADY finished", 0) == ()


def test_notes_are_not_doctrine():
    verdict = _classify_text("notes/how_we_work.md", "Overview. Steps: one, two, three.\n")
    assert verdict.primary == "Knowledge"
    assert "Doctrine" not in verdict.all_classes


def test_architecture_research_is_not_accepted_architecture():
    verdict = _classify_text(
        "research/architecture_options.md",
        "We could use option A. Trade-offs across the Dispatch freight lane.\n")
    assert verdict.primary == "Research"
    assert verdict.dispatch_related is True
    assert "dispatch" in verdict.dispatch_signals


def test_when_in_doubt_unknown():
    verdict = _classify_text("blob", "")
    assert verdict.primary == "Unknown"
    assert any("Unknown is the answer" in reason for reason in verdict.reasons)


def test_binary_content_evidence_is_suppressed():
    verdict = _classify_text(
        "archive/thing.dat", "Decision: approved by Dana Fixture", text_confidence="binary")
    assert verdict.content_evidence_used is False
    assert verdict.attestation_claims == 0
    assert verdict.decision_candidate is False
    assert any("content evidence suppressed" in reason for reason in verdict.reasons)


def test_an_unreadable_file_classifies_unknown_with_its_reason():
    scanned = scanner.ScannedFile(
        relpath="locked/dispatch_plan.md", absolute="/x", name="dispatch_plan.md",
        suffix=".md", size=0, modified="", sha256="",
        read_error="PermissionError: denied", text_confidence="unread",
    )
    verdict = classifier.classify(scanned)
    assert verdict.primary == "Unknown"
    assert verdict.reasons[0].startswith("unreadable.error")
    # Underscores are word characters, so the path signal only matches because
    # `signal_haystack` normalises separators first.
    assert verdict.dispatch_related is True
    assert classifier.signal_haystack("a_b-c") == "a b c"


def test_prompt_assets_and_library_candidates_are_flagged():
    prompt = _classify_text("assets/system_prompt.md", "You are a helpful dispatcher.\n")
    assert prompt.prompt_asset is True
    library = _classify_text("forms/onboarding_checklist.md", "Checklist for new drivers.\n")
    assert library.library_candidate is True
    personal = _classify_text("personal/tax_checklist.md", "Checklist of tax documents.\n")
    assert personal.primary == "Personal"
    assert personal.library_candidate is False


def test_superseded_and_unresolved_markers_are_counted_not_quoted():
    verdict = _classify_text(
        "old/plan.md",
        "This is deprecated and superseded. TODO: revisit. Open question: which lane?\n")
    assert verdict.superseded_markers >= 2
    assert verdict.unresolved_question_markers >= 2
    assert "Historical" in verdict.all_classes


def test_every_assigned_class_is_in_the_closed_vocabulary(sandbox: Path, output_root: Path):
    result = _run(sandbox, output_root)
    for record in result.files:
        assert record["primary_class"] in classifier.CLASSES
        for name in record["secondary_classes"]:
            assert name in classifier.CLASSES


# --------------------------------------------------------------------------- duplicates

def test_exact_duplicates_are_grouped_by_hash(tmp_path: Path):
    root = tmp_path / "Play Pen"
    body = "identical content for both copies\n"
    _write(root / "a.md", body)
    _write(root / "sub" / "b.md", body)
    _write(root / "different.md", "something else entirely\n")
    (root / "empty_one.md").write_text("", encoding="utf-8")
    (root / "empty_two.md").write_text("", encoding="utf-8")

    result = survey.run_survey(root, root / "Dispatch", moment=MOMENT)
    exact = result.duplicate_report["exact"]
    assert len(exact) == 1
    group = exact[0]
    assert group["members"] == ["a.md", "sub/b.md"]
    assert "byte-identical" in group["evidence"] and group["signal"] == "sha256_identical"
    # Empty files share a hash but are not meaningfully duplicates of each other.
    assert not any("empty_one.md" in item["members"] for item in exact)

    by_path = {record["relpath"]: record for record in result.files}
    assert "Duplicate" in by_path["a.md"]["secondary_classes"]
    assert by_path["a.md"]["duplicate_of"] == ["sub/b.md"]


def test_near_duplicates_by_name_and_size(tmp_path: Path):
    root = tmp_path / "Play Pen"
    _write(root / "plan.md", "x" * 1000)
    _write(root / "Copy of plan (2).md", "y" * 1010)
    result = survey.run_survey(root, root / "Dispatch", moment=MOMENT)
    near = [group for group in result.duplicate_report["near"]
            if group["signal"] == "normalised_name_and_size"]
    assert len(near) == 1
    assert "copy markers are stripped" in near[0]["evidence"]
    assert "spread" in near[0]["evidence"]


def test_near_duplicates_by_token_shingling(tmp_path: Path):
    root = tmp_path / "Play Pen"
    base = " ".join(f"word{index}" for index in range(80))
    _write(root / "alpha.md", base)
    _write(root / "totally_different_name.md", base + " and a short tail")
    result = survey.run_survey(root, root / "Dispatch", moment=MOMENT)
    near = [group for group in result.duplicate_report["near"]
            if group["signal"] == "token_shingling"]
    assert len(near) == 1
    assert "Jaccard" in near[0]["evidence"]
    assert near[0]["score"] >= duplicates.NEAR_DUPLICATE_THRESHOLD


def test_exact_matches_are_not_reported_again_as_near_matches(tmp_path: Path):
    root = tmp_path / "Play Pen"
    body = " ".join(f"token{index}" for index in range(100))
    _write(root / "one.md", body)
    _write(root / "two.md", body)
    result = survey.run_survey(root, root / "Dispatch", moment=MOMENT)
    assert len(result.duplicate_report["exact"]) == 1
    assert result.duplicate_report["near"] == []


def test_shingling_ceiling_is_reported_as_a_stated_gap(tmp_path: Path, monkeypatch):
    monkeypatch.setattr(duplicates, "MAX_SHINGLE_CANDIDATES", 1)
    root = tmp_path / "Play Pen"
    _write(root / "a.md", "alpha beta gamma delta epsilon zeta eta theta\n")
    _write(root / "b.md", "one two three four five six seven eight nine\n")
    result = survey.run_survey(root, root / "Dispatch", moment=MOMENT)
    notes = result.duplicate_report["notes"]
    assert notes and "stated gap" in notes[0]
    # The gap is stated in the report, not only in the JSON.
    rendered = dict(reports.generate_all(result.to_dict()))
    assert "Gaps in this analysis" in rendered[f"POSSIBLE_DUPLICATES_{RUN_ID}.md"]


def test_normalise_name_strips_stacked_copy_markers():
    assert duplicates.normalise_name("Copy of plan - Copy (2).md") == "plan"
    assert duplicates.normalise_name("report_v3.docx") == "report"
    assert duplicates.normalise_name("minutes-2026-01-02.md") == "minutes"
    assert duplicates.normalise_name("minutes_1_2_26.md") == "minutes"
    assert duplicates.normalise_name("plain") == "plain"


def test_shingles_and_jaccard_edges():
    assert duplicates.shingles("too short") == frozenset()
    assert duplicates.jaccard(frozenset(), frozenset({"a"})) == 0.0
    left = duplicates.shingles(" ".join(str(index) for index in range(40)))
    assert duplicates.jaccard(left, left) == 1.0


# --------------------------------------------------------------------------- sensitive material

def test_a_fabricated_credential_never_reaches_any_output(sandbox: Path, output_root: Path):
    result = _run(sandbox, output_root)
    written = _write_all(result, output_root)
    assert written

    for path in written:
        blob = path.read_text(encoding="utf-8")
        assert FAKE_SECRET not in blob, f"{path.name} leaked the credential"
        assert FAKE_AWS_KEY not in blob, f"{path.name} leaked the access key"
        assert "fixture@example.invalid" not in blob, f"{path.name} leaked an email address"

    # And it really did detect it -- the test would otherwise pass vacuously.
    findings = [item for item in result.sensitive_findings
                if item["relpath"] == "secrets/deploy_notes.txt"]
    detectors = {item["detector"] for item in findings}
    assert {"credential_assignment", "aws_access_key_id", "email_address"} <= detectors
    assert all(set(item) == {"relpath", "category", "detector", "hits"} for item in findings)


def test_sensitive_report_carries_paths_and_categories_only(sandbox: Path, output_root: Path):
    result = _run(sandbox, output_root)
    written = _write_all(result, output_root)
    report = next(path for path in written if path.name.startswith("SENSITIVE_MATERIAL_REPORT"))
    text = report.read_text(encoding="utf-8")
    assert "secrets/deploy_notes.txt" in text
    assert "credentials" in text
    for category in sensitive.CATEGORIES:
        assert category in text
    assert FAKE_SECRET not in text


def test_sensitive_finding_has_no_field_that_could_hold_content():
    fields = set(sensitive.SensitiveFinding.__dataclass_fields__)
    assert fields == {"relpath", "category", "detector", "hits"}


def _detect_text(name: str, body: str, confidence: str = "text"):
    scanned = scanner.ScannedFile(
        relpath=name, absolute="/x", name=name.rsplit("/", 1)[-1], suffix=".txt",
        size=len(body), modified="", sha256="0" * 64, sample=body,
        sample_bytes=len(body), text_confidence=confidence,
    )
    return {finding.detector: finding for finding in sensitive.detect(scanned)}


def test_each_sensitive_category_has_a_working_detector():
    assert "private_key_block" in _detect_text(
        "keys.txt", "-----BEGIN RSA PRIVATE KEY-----\n")
    assert "bearer_token_header" in _detect_text(
        "req.txt", "Authorization: Bearer abcdefghijklmnop\n")
    assert "url_embedded_credentials" in _detect_text(
        "u.txt", "https://user:hunter2@example.invalid/path\n")
    assert "credential_filename" in _detect_text("deploy/id_rsa", "")
    assert "us_ssn" in _detect_text("hr.txt", "SSN 123-45-6789\n")
    assert "date_of_birth" in _detect_text("hr.txt", "Date of birth: 1970-01-01\n")
    assert "government_id" in _detect_text("hr.txt", "CDL number: 12345\n")
    assert "personal_filename" in _detect_text("people/resume_final.txt", "")
    assert "bank_routing" in _detect_text("fin.txt", "Routing number: 123456789\n")
    assert "bank_account" in _detect_text("fin.txt", "Account number: 998877665\n")
    assert "financial_filename" in _detect_text("money/payroll_jan.txt", "")
    assert "confidentiality_marking" in _detect_text(
        "doc.txt", "Strictly confidential — do not distribute\n")
    assert "third_party_filename" in _detect_text("legal/nda_acme.txt", "")


def test_payment_card_detection_is_luhn_gated():
    assert "payment_card" in _detect_text("pay.txt", "card 4111 1111 1111 1111\n")
    assert "payment_card" not in _detect_text("log.txt", "sequence 1234 5678 9012 3456\n")
    assert sensitive._luhn_ok("4111111111111111") is True
    assert sensitive._luhn_ok("123") is False


def test_path_detectors_still_fire_on_an_unreadable_file():
    detectors = _detect_text("keys/id_rsa", "", confidence="unread")
    assert "credential_filename" in detectors
    assert "credential_assignment" not in detectors


# --------------------------------------------------------------------------- reports

def _all_outputs(sandbox: Path, output_root: Path) -> dict[str, str]:
    result = _run(sandbox, output_root)
    return {name: text for name, text in reports.generate_all(result.to_dict())}


def test_every_output_carries_the_required_header(sandbox: Path, output_root: Path):
    outputs = _all_outputs(sandbox, output_root)
    assert len(outputs) == 11
    for name, text in outputs.items():
        if name.endswith(".json"):
            continue
        assert "Claude Code" in text, name
        assert str(sandbox) in text, name
        assert str(output_root) in text, name
        assert survey.READ_ONLY_DECLARATION in text, name
        assert survey.AUTHORITY_DECLARATION in text, name
        assert "2026-08-24" in text, name


def test_the_nine_required_documents_are_produced(sandbox: Path, output_root: Path):
    outputs = set(_all_outputs(sandbox, output_root))
    for base in (
        "SANDBOX_FILE_INVENTORY", "SANDBOX_KNOWLEDGE_MAP", "DISPATCH_RESEARCH_CANDIDATES",
        "POSSIBLE_DUPLICATES", "GOVERNANCE_AND_DOCTRINE_CANDIDATES",
        "MIKE_DECISION_CANDIDATES", "SENSITIVE_MATERIAL_REPORT",
        "PROPOSED_FOLDER_STRUCTURE", "PROPOSED_ORGANIZATION_ACTIONS",
    ):
        assert any(name.startswith(base) for name in outputs), base
    assert f"SANDBOX_FILE_INVENTORY_{RUN_ID}.csv" in outputs
    assert f"sandbox_survey_{RUN_ID}.json" in outputs


def test_the_knowledge_map_states_the_interpretation_rules_verbatim(
    sandbox: Path, output_root: Path
):
    text = _all_outputs(sandbox, output_root)[f"SANDBOX_KNOWLEDGE_MAP_{RUN_ID}.md"]
    for rule in classifier.INTERPRETATION_RULES:
        assert rule in text, rule


def test_the_inventory_csv_parses_and_carries_every_required_column(
    sandbox: Path, output_root: Path
):
    text = _all_outputs(sandbox, output_root)[f"SANDBOX_FILE_INVENTORY_{RUN_ID}.csv"]
    assert text.startswith("# Generated by: Claude Code")
    assert survey.READ_ONLY_DECLARATION in text
    body = "\n".join(line for line in text.splitlines() if not line.startswith("#"))
    rows = list(csv.DictReader(io.StringIO(body)))
    assert rows
    for column in ("path", "size_bytes", "modified_utc", "sha256", "primary_class",
                   "secondary_classes", "dispatch_related"):
        assert column in rows[0]
    assert {row["dispatch_related"] for row in rows} <= {"Y", "N"}


def test_proposed_actions_are_numbered_reversible_and_unexecuted(
    sandbox: Path, output_root: Path
):
    text = _all_outputs(sandbox, output_root)[f"PROPOSED_ORGANIZATION_ACTIONS_{RUN_ID}.md"]
    assert "NOTHING IN THIS DOCUMENT HAS BEEN EXECUTED" in text
    assert "### 1." in text and "### 2." in text
    assert text.count("**Status:** proposed — not executed") >= 2
    assert "Reversal:" in text
    assert "Nothing is deleted. Ever." in text


def test_exact_duplicates_produce_a_numbered_move_proposal(tmp_path: Path):
    root = tmp_path / "Play Pen"
    body = "identical content in two places\n"
    _write(root / "a.md", body)
    _write(root / "backup" / "a.md", body)
    result = survey.run_survey(root, root / "Dispatch", moment=MOMENT)
    rendered = dict(reports.generate_all(result.to_dict()))

    duplicates_doc = rendered[f"POSSIBLE_DUPLICATES_{RUN_ID}.md"]
    assert "byte-identical" in duplicates_doc
    actions = rendered[f"PROPOSED_ORGANIZATION_ACTIONS_{RUN_ID}.md"]
    assert "byte-identical groups" in actions
    assert "70_Historical/duplicates/" in actions
    assert "No deletion, no merge" in actions


def test_reports_are_pure_functions_over_the_dict(sandbox: Path, output_root: Path):
    result = _run(sandbox, output_root)
    data = result.to_dict()
    first = reports.generate_all(data)
    second = reports.generate_all(data)
    assert first == second


def test_absent_templates_claim_nothing_about_the_sandbox():
    result = survey.absent_result(
        r"D:\Sandbox\Play Pen", r"D:\Sandbox\Play Pen\Dispatch",
        reason="not run: no access to the machine that holds the folder",
        moment=MOMENT,
    )
    assert result.status == "ABSENT"
    outputs = dict(reports.generate_all(result.to_dict()))
    assert len(outputs) == 11
    for name, text in outputs.items():
        if name.endswith(".json"):
            continue
        assert "THIS SURVEY HAS NOT BEEN RUN" in text, name
        assert "ABSENT" in text, name
        assert survey.READ_ONLY_DECLARATION in text, name
        assert survey.AUTHORITY_DECLARATION in text, name
        if name.endswith(".md"):
            assert "`ABSENT`" in text, name
            assert "not performed" in text, name
    csv_text = outputs[f"SANDBOX_FILE_INVENTORY_{RUN_ID}.csv"]
    assert "THIS SURVEY HAS NOT BEEN RUN" in csv_text
    assert "ABSENT" in csv_text
    body = [line for line in csv_text.splitlines() if not line.startswith("#")]
    assert len(body) == 1, "an ABSENT inventory lists no files"


def test_absent_counts_are_all_zero():
    result = survey.absent_result("/x", "/x/out", reason="not run", moment=MOMENT)
    counts = result.counts()
    assert counts["files"] == 0 and counts["total_bytes"] == 0
    assert counts["by_primary_class"]["Unknown"] == 0


def test_no_report_quotes_file_content(sandbox: Path, output_root: Path):
    """Sentinel phrases from the input tree appear in no generated document."""
    marker = "ZZQX-CONTENT-MARKER-NEVER-QUOTED"
    _write(sandbox / "notes" / "marked.md", f"Dispatch note. {marker}\n")
    outputs = _all_outputs(sandbox, output_root)
    for name, text in outputs.items():
        assert marker not in text, name
    assert any("notes/marked.md" in text for text in outputs.values())


# --------------------------------------------------------------------------- CLI

def test_cli_runs_and_reports(sandbox: Path, output_root: Path, capsys):
    code = cli.main(["--sandbox-root", str(sandbox), "--output-root", str(output_root)])
    assert code == 0
    out = capsys.readouterr().out
    assert "READ-ONLY PASS, NO FILES WERE MODIFIED" in out
    assert "files inventoried" in out
    assert "PROPOSED_ORGANIZATION_ACTIONS has not been executed" in out
    assert len(list(output_root.iterdir())) == len(reports.DOCUMENTS)


def test_cli_dry_run_writes_nothing(sandbox: Path, output_root: Path, capsys):
    before = _snapshot(sandbox)
    code = cli.main(["--sandbox-root", str(sandbox), "--dry-run"])
    assert code == 0
    assert "would write" in capsys.readouterr().out
    assert not output_root.exists()
    assert _snapshot(sandbox) == before


def test_cli_defaults_the_output_folder_inside_the_sandbox(sandbox: Path):
    resolved = cli._resolve_output_argument(str(sandbox), None)
    assert Path(resolved) == sandbox / "Dispatch"
    assert cli._resolve_output_argument(str(sandbox), "/explicit") == "/explicit"
    assert cli.DEFAULT_SANDBOX_ROOT == r"D:\Sandbox\Play Pen"


def test_cli_refuses_loudly_on_a_safety_violation(tmp_path: Path, capsys):
    inside = tmp_path / "Play Pen"
    inside.mkdir()
    code = cli.main([
        "--sandbox-root", str(inside), "--output-root", str(tmp_path / "Elsewhere"),
    ])
    assert code == 2
    err = capsys.readouterr().err
    assert err.startswith("REFUSED:")
    assert "Nothing was read and nothing was written." in err
    assert not (tmp_path / "Elsewhere").exists()


def test_cli_rejects_a_nonsense_max_bytes(capsys):
    assert cli.main(["--sandbox-root", ".", "--max-bytes", "0"]) == 2
    assert "--max-bytes must be at least 1" in capsys.readouterr().err


def test_cli_parser_documents_the_defaults():
    parser = cli.build_parser()
    text = parser.format_help()
    assert "--sandbox-root" in text and "--output-root" in text
    assert "--dry-run" in text and "--max-bytes" in text
    args = parser.parse_args([])
    assert args.sandbox_root == cli.DEFAULT_SANDBOX_ROOT
    assert args.output_root is None and args.dry_run is False


# --------------------------------------------------------------------------- assembly

def test_survey_result_round_trips_through_its_dict(sandbox: Path, output_root: Path):
    data = _run(sandbox, output_root).to_dict()
    assert data["tool"] == "dispatch.sandbox_survey"
    assert data["status"] in ("MANUAL", "ABSENT")
    assert data["interpretation_rules"] == list(classifier.INTERPRETATION_RULES)
    assert data["classes"] == list(classifier.CLASSES)
    assert {anchor["anchor_id"] for anchor in data["locked_doctrine"]} == {
        anchor.anchor_id for anchor in classifier.LOCKED_DOCTRINE
    }
    assert data["read_only_declaration"] == survey.READ_ONLY_DECLARATION


def test_status_words_come_only_from_the_locked_truth_vocabulary():
    vocabulary = {
        "LIVE", "CONFIGURED", "UNCONFIGURED", "SIMULATED", "UNAVAILABLE",
        "MANUAL", "ABSENT", "UNVERIFIED",
    }
    assert survey.STATUS_COMPLETE in vocabulary
    assert survey.STATUS_ABSENT in vocabulary


def test_make_run_id_is_utc_and_sortable():
    earlier = survey.make_run_id(datetime(2026, 1, 1, tzinfo=timezone.utc))
    later = survey.make_run_id(datetime(2026, 1, 2, tzinfo=timezone.utc))
    assert earlier < later
    assert later.endswith("Z")
