"""The Platform Neutral Contract Doctrine, enforced across everything.

    Doctrine -> Contract -> Adapter -> Provider
    Provider must never become the contract.

Joe's intelligence is rented and a rental is replaceable by definition. The
moment a provider's concepts -- its IDs, its naming, its workflow assumptions --
reach the endpoints, the data structures, the audit schema or the authority
model, the rental becomes a marriage. Dispatch would then carry somebody else's
product decisions inside its own record of what happened, and the audit log is
the one thing that has to outlive every provider in it.

WHY THIS FILE SCANS RATHER THAN LISTS
=====================================

An earlier guard named three files. That protects those three files and nothing
else, and the next contract module written would not be covered -- a guard with
a hand-kept list is a guard that decays. This scans every authoritative
directory and requires the *exemptions* to be listed instead, so the default for
new code is protected.

Vendor names are allowed in exactly one place: `adapters/`. That is what the
directory is for.
"""

from __future__ import annotations

import pathlib
import re

import pytest

#: Provider concepts. Names, platforms, SDKs and identifiers that belong to a
#: vendor rather than to freight.
PROVIDER_TERMS = (
    "copilot", "microsoft", "m365", "office365", "msal", "azure",
    "graph.microsoft", "sharepoint", "onedrive", "powerapps", "power automate",
    "dataverse", "teams", "openai", "anthropic", "claude", "gemini", "bedrock",
)

#: Text that contains a provider term without being a provider reference.
#: Removed before the scan, because the doctrine is about *depending on* a
#: provider -- not about being unable to name a document, a repository, or the
#: models a detector is built to recognise. Each pattern is a deliberate act
#: with its reason attached, exactly as an exemption is.
#:
#: If one of these strings changes, the guard fires again and the change is
#: re-approved rather than inherited silently. That is intended.
NOT_A_PROVIDER = (
    # This repository's own cold-start brief. Named in 5 files by design --
    # CLAUDE.md section 6 is the status vocabulary every module cites.
    r"claude\.md",
    # The Claude-2 / Claude-3 / Jules-3 doctrine repositories in this
    # ecosystem. Repository names, not runtime dependencies.
    r"claude-\d",
    r"jules-\d",
    # Build attribution on generated reports. Records who wrote a document;
    # nothing imports it and no code path depends on it.
    r"claude\s+code",
    # dispatch/sandbox_survey/classifier.py's _AI_GENERATED detector. A guard
    # that spots AI-written text has to name the models it looks for, the same
    # way this file has to name the providers it forbids.
    r"generated by \(chatgpt\|claude\|gpt\|copilot\|gemini\|bard\)",
)

_NOT_A_PROVIDER_RE = re.compile("|".join(NOT_A_PROVIDER))

#: Everything authoritative. Doctrine and contract live here; nothing in these
#: trees may name a provider.
CONTRACT_ROOTS = ("dispatch", "portal")

#: The only place provider names belong.
ADAPTER_ROOT = "adapters"

#: Files inside the contract roots that are exempt, each with the reason. A new
#: exemption is a deliberate act with a justification attached, not a quiet
#: addition to a list.
EXEMPT = {
    # Outlook is a provider, and these are its adapters. They sit under
    # dispatch/ for historical reasons and are adapters in everything but
    # location; the contract does not import them, it asks a registry.
    "dispatch/connectors/outlook_mail.py": "Outlook adapter",
    "dispatch/connectors/registry.py": "names the adapters it may load",
    "dispatch/connectors/__init__.py": "connector registry docstring",
    "dispatch/scheduling.py": "Outlook calendar adapter behind CalendarPort",
    # The mail path predates the contract and is provider-specific throughout.
    "cin_lite/email_delivery.py": "SMTP/provider mail path",
    # The legacy settings page reports whether provider credentials are
    # configured, which is a display of adapter state rather than contract.
    # Narrow by test: see test_the_settings_exemption_stays_small.
    "portal/routes/pages.py": "settings page displays provider config status",
    # Merged from `main` 2026-09-05. Each is an adapter or a security control
    # that must name a provider in order to do its job.
    "dispatch/connectors/outlook_connector.py": "Outlook adapter -- same role as outlook_mail.py",
    "dispatch/connectors/contract.py": "SECRET_ENV_VARS must name the keys it redacts, or they leak",
    "portal/models/integrations_registry.py": "credential store; its security note names the secrets it holds",
    # Moved out of cin_lite/agents/ on 2026-09-09 because it is freight work:
    # fuel-receipt scanning for the driver portal and the dispatch API. It names
    # the model it calls, so it sits among the connectors rather than at the top
    # of dispatch/ -- an adapter in role, like outlook_mail.py beside it.
    "dispatch/connectors/receipt_vision.py": "vision adapter -- names the model it calls",
}

#: How many provider references the settings exemption may carry before it
#: stops being an exemption and starts being a hole.
SETTINGS_ALLOWANCE = 3


def _scannable(path) -> str:
    """The file's text with the known non-provider phrases removed."""
    text = path.read_text(encoding="utf-8", errors="ignore").lower()
    return _NOT_A_PROVIDER_RE.sub("", text)


def _files():
    for root in CONTRACT_ROOTS:
        for path in pathlib.Path(root).rglob("*.py"):
            rel = path.as_posix()
            if rel in EXEMPT:
                continue
            yield rel, path


class TestNoProviderInsideTheContract:
    def test_every_authoritative_file_is_clean(self):
        """Scans rather than lists, so new contract code is protected by
        default."""
        offences = []
        for rel, path in _files():
            text = _scannable(path)
            for term in PROVIDER_TERMS:
                if term in text:
                    offences.append("%s names '%s'" % (rel, term))
        assert offences == [], offences

    def test_the_joe_contract_specifically(self):
        """The files the doctrine calls the contract, checked by name as well,
        so a refactor that moves them cannot quietly drop the cover."""
        for rel in ("portal/routes/joe_api.py", "dispatch/joe_authority.py",
                    "dispatch/audit.py"):
            text = pathlib.Path(rel).read_text(encoding="utf-8").lower()
            for term in PROVIDER_TERMS:
                assert term not in text, "%s names '%s'" % (rel, term)

    def test_data_structures_carry_no_provider_concepts(self):
        """Audit entries and authority records are read years later."""
        from dispatch import audit

        entry = audit.record.__doc__ or ""
        assert not any(t in entry.lower() for t in PROVIDER_TERMS)

        from dispatch import joe_authority as authority

        for name in dir(authority):
            if name.startswith("_"):
                continue
            assert not any(t in name.lower() for t in PROVIDER_TERMS), name

    def test_the_audit_schema_is_provider_neutral(self):
        """Written once, read forever. A field named for a product outlives the
        product."""
        from dispatch import audit

        entry = audit.record(action="probe", driver="test",
                             channel=audit.CHANNEL_API)
        for key in entry:
            assert not any(t in key.lower() for t in PROVIDER_TERMS), key

    @pytest.mark.parametrize("term", ["copilot", "microsoft", "teams", "azure"])
    def test_the_guard_actually_catches_something(self, term):
        """A guard that cannot fail is not a guard."""
        assert term in PROVIDER_TERMS


class TestExemptionsAreDeliberate:
    def test_every_exemption_carries_a_reason(self):
        for path, reason in EXEMPT.items():
            assert reason and len(reason) > 8, path

    def test_every_exempt_file_exists(self):
        """A stale exemption is cover for a file nobody is checking."""
        for path in EXEMPT:
            assert pathlib.Path(path).exists(), path

    def test_the_settings_exemption_stays_small(self):
        """A whole-file exemption on a large module is a hole. This one is
        allowed because a settings page legitimately reports whether provider
        credentials are configured -- and it is checked so it cannot grow into
        provider logic."""
        text = pathlib.Path("portal/routes/pages.py").read_text(
            encoding="utf-8").lower()
        hits = sum(text.count(term) for term in PROVIDER_TERMS)
        assert hits <= SETTINGS_ALLOWANCE, (
            "%d provider references in the settings page; the exemption covers "
            "a status display, not provider logic" % hits)

    def test_the_exempt_files_are_adapters_in_role(self):
        """Each one is a provider adapter, whatever directory it sits in."""
        for path in EXEMPT:
            text = pathlib.Path(path).read_text(encoding="utf-8").lower()
            assert ("adapter" in text or "connector" in text
                    or "smtp" in text or "settings" in text), path


class TestAdaptersAreWhereProvidersLive:
    def test_the_adapter_directory_exists_and_says_what_it_is_for(self):
        readme = pathlib.Path(ADAPTER_ROOT, "README.md")
        assert readme.exists()
        text = readme.read_text(encoding="utf-8").lower()
        assert "contracts first" in text
        assert "adapter" in text

    def test_the_contract_does_not_import_an_adapter_directly(self):
        """It asks a registry. An import would make the provider a dependency
        of the contract rather than a choice behind it."""
        contract = pathlib.Path("portal/routes/joe_api.py").read_text(
            encoding="utf-8")
        assert "from adapters" not in contract
        assert "import adapters" not in contract


class TestTheContractMatchesTheDoctrine:
    """The contracts in code are exactly the ratified eight -- not 'at least',
    not 'roughly'.

    **Seven since 2026-09-06**, when Opportunity Capture was ratified as the
    seventh contract and built under EXEC-ORDER v1.0 Step 3. **Eight since
    2026-09-08**, when the Owner ruled the Mission Card template published.

    **Where "seven" comes from, named exactly.** §8.1 item 1 lists **six**
    endpoints; the seventh is ratified in `OPPORTUNITY_CAPTURE_PLAN.md` §2. The
    ground rule's phrase *"§8.1 (seven, including Opportunity Capture)"* is loose
    on that point, and a test asserting equality has to name its source or it
    drifts. So each entry below carries the document that ratified it, and
    `test_six_come_from_8_1_and_one_does_not` keeps the discrepancy visible
    rather than letting it be tidied away.

    **Equality, not sufficiency.** Adding an endpoint beyond spec is Class 3 --
    never Code's -- so a surplus fails as loudly as a gap.
    """

    #: (method, rule) -> the document and section that ratified it.
    RATIFIED = {
        ("GET", "/api/joe/mission-status"): "MISSION §8.1",
        ("POST", "/api/joe/driver-status"): "MISSION §8.1",
        ("GET", "/api/joe/facility-intel/<path:facility_id>"): "MISSION §8.1",
        ("GET", "/api/joe/schedule-fit"): "MISSION §8.1",
        ("POST", "/api/joe/send-notice"): "MISSION §8.1",
        ("PATCH", "/api/joe/mission-record/<path:mission_id>"): "MISSION §8.1",
        ("POST", "/api/joe/opportunity"): "OPP-CAPTURE §2",
        # Ruled 2026-09-08. The Owner asked why JOE did not already know the
        # form -- "How does Joe not know the fields in this document?" -- and
        # the answer was that I had copied eleven of the Mission Card's
        # thirty-three fields into JOE and written my own questions for them.
        # He ruled: "build B, publish the template from Dispatch."
        ("GET", "/api/joe/mission-template"): "DECISION_LOG 2026-09-08",
    }

    SPECIFIED = set(RATIFIED)

    def _live(self):
        from portal.app import create_app

        app = create_app()
        return {(m, str(r.rule)) for r in app.url_map.iter_rules()
                if "/api/joe" in str(r.rule)
                for m in r.methods if m in ("GET", "POST", "PATCH", "PUT",
                                            "DELETE")}

    def test_exactly_the_eight(self):
        assert self._live() == self.SPECIFIED

    def test_there_are_eight(self):
        assert len(self.SPECIFIED) == 8

    def test_nothing_exceeds_the_specification(self):
        """Adding an endpoint beyond spec is Class 3, never Code's."""
        assert self._live() - self.SPECIFIED == set()

    def test_the_template_is_a_read_of_a_definition_not_of_operational_truth(self):
        """Why an eighth endpoint did not need a new class of thinking.

        It publishes the *shape* of the form -- keys, labels, the question to
        ask -- which is identical on an empty node and a busy one. No load, no
        driver and no record passes through it, so nothing it returns could ever
        be a second copy of operational truth.
        """
        from dispatch import mission_template as mt

        published = {"key", "label", "section", "required", "hint", "spoken",
                     "choices", "opportunity_field"}
        assert published <= (set(vars(mt.TEMPLATE[0])) | {"opportunity_field"})

    def test_six_come_from_8_1_and_two_do_not(self):
        """The Step 0 finding, held in place by a test. If someone later claims
        all seven come from §8.1, this fails and the discrepancy is re-read
        rather than re-buried."""
        by_source = {}
        for contract, source in self.RATIFIED.items():
            by_source.setdefault(source, []).append(contract)
        assert len(by_source["MISSION §8.1"]) == 6
        assert by_source["OPP-CAPTURE §2"] == [("POST", "/api/joe/opportunity")]

    def test_nothing_specified_is_missing(self):
        assert self.SPECIFIED - self._live() == set()

    def test_there_is_no_commit_endpoint(self):
        """Class 3 is enforced by absence. A door with a lock is still a door
        where doctrine says there should be none."""
        assert not any("commit" in rule for _, rule in self._live())


class TestTheGatewayCheckIsAnAdapter:
    """A data gateway is a provider concept, so the check lives in adapters/
    and the contract knows nothing about it."""

    def test_it_lives_in_adapters(self):
        assert pathlib.Path("adapters/gateway_health.py").exists()
        assert not pathlib.Path("dispatch/gateway_health.py").exists()

    def test_no_contract_file_imports_it(self):
        for rel, path in _files():
            text = path.read_text(encoding="utf-8", errors="ignore")
            assert "gateway_health" not in text, rel

    def test_it_reports_only_the_doctrine_vocabulary(self):
        from adapters import gateway_health

        assert gateway_health.check()["status"] in (
            gateway_health.LIVE, gateway_health.CONFIGURED,
            gateway_health.UNVERIFIED)

    def test_it_never_infers_a_status(self):
        """An owner reporting a gateway as set up is information about a
        belief, not evidence about a machine."""
        source = pathlib.Path("adapters/gateway_health.py").read_text(
            encoding="utf-8")
        assert "def _service_state" in source
        assert "os.path.isdir" in source
        assert "assume" not in source.lower().replace("assumed", "")

    def test_a_check_that_cannot_run_is_unverified_not_a_guess(self):
        from adapters import gateway_health

        result = gateway_health.check()
        assert result["checked"] is True
        if not result["service_found"] and not result["installed"]:
            assert result["status"] == gateway_health.UNVERIFIED
